### ISSUE TITLE
Magnifying glass icon is off-center while searching

### ISSUE THREAD

**Issue by MaestroGoldring** [OpenBeta/open-tacos#1008]
## Steps to reproduce:
1. Go to the rock climbing catalogue page on mobile webpage.
2. Touch the magnifying glass to begin a search.
3. When the magnifying glass moves to the top left corner within the orange circle, it's off-center. (Not the biggest deal, but a good first fix.)

## Screenshots
![image](https://github.com/OpenBeta/open-tacos/assets/136112034/6dae9329-d6cb-4bca-ac18-dbf26075007c)
## Expected Behavior
Quite simply, the icon should be centered within the orange background.

## Current Behavior
As you can see in the screenshot, it renders but off center.

## Browser & version
Safari 16

## Operating system
iOS 16.7.2

**Comment by Haviles04** [comment]
Can I work on this?

**Comment by vnugent** [comment]
Sure!
