### ISSUE TITLE
Improve area map

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1009]
**What would you like to be able to do? Please describe.**
When there is only 1 point on the map, it's hard to tell where it is without context because the map is zoomed in really close.  

To do:
- [ ] Switch to map style to 'light' (see [code](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/area/areaMap.tsx#L76))
- [ ] Increase padding when `props.subAreas.length === 0`

Map padding object: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/area/areaMap.tsx#L54C9-L54C16

**How important is this to you** (Please pick one)
- Nice-to-have

**Note**:  email viet at openbeta dot io for Mapbox API dev key.

## How to reproduce:
- prod: https://openbeta.io/crag/1108ed31-163f-5097-8573-0932141bf135
- local dev/staging: https://stg.openbeta.io/crag/63b0fdda-319f-5823-88a0-7d208371751f

### Current
<img width="834" alt="Screenshot 2023-11-02 at 9 33 29 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/c71b6b1f-be8f-438d-b4f5-42e3a8f3d834">

### What we want
<img width="827" alt="Screenshot 2023-11-02 at 9 34 43 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/b33a2a7d-961f-4550-b13b-c5fb1ca2f58d">

**Comment by ShravaniRoy** [comment]
Hi, @vnugent. I want to work on this. I have the project set up on my machine and am able to reproduce the issue. Please assign this to me

**Comment by vnugent** [comment]
Hi @ShravaniRoy 
I believe @Ali-muhammed7040 is already working on this.  I'll create new issues in the upcoming days and will tag you.
