### ISSUE TITLE
Use new media servers

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1013]
**What would you like to be able to do? Please describe.**
We now have 2 new media services, `media-stg.openbeta.io` and `media.openbeta.io`. Update the code to use the new url.

### Contributor To-do:
- [ ] In .env update  `NEXT_PUBLIC_CDN_URL` to **https://media-stg.openbeta.io**

### Admin to-do:
- [ ] Update NEXT_PUBLIC_CND_URL in Vercel dashboard to media.openbeta.io

Related issue: https://github.com/OpenBeta/open-tacos/issues/944

**How important is this to you** (Please pick one)
- Important

**Comment by vnugent** [comment]
@ShravaniRoy this is a 1-line change task. Let me know if you're interested.

**Comment by ShravaniRoy** [comment]
@vnugent yes, I am interested. Please assign it to me.

**Comment by subhajit20** [comment]
hey @vnugent  , can I work on this?
