### ISSUE TITLE
How to contribute page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#102]
Add a new how-to page or update About page (https://tacos.openbeta.io/about) explaining how to contribute/edit routes.

**Comment by CocoisBuggy** [comment]
I'll make a start on this one, I'll add some scaffolding for growing a tutorial base as we move forward

**Comment by vnugent** [comment]
I filed this issue last year before we have this standalone docs site https://docs.openbeta.io

The docs can be built independent of the frontend app and also has full text search.

Can you look into expanding the content, maybe the specifics on how to add new areas and soon climbs?

https://docs.openbeta.io/how-to-contribute/overview

**Comment by CocoisBuggy** [comment]
Absolutely. I see it's using Docusaurus which makes a lot of sense I think. Can we close this issue here?
