### ISSUE TITLE
Refactor "Large Component" code smell

### ISSUE THREAD

**Issue by ovictorpa** [OpenBeta/open-tacos#1029]
We analyzed the project and using the "reactsniffer" tool we found some code smells "Too many props", we suggested a refactoring and we will work on it to contribute to the project. We opened this issues for research into the software quality discipline that is working with free software contributions.

**Comment by musoke** [comment]
> We analyzed the project

Who is "we" in this context?

**Comment by trevornei** [comment]
Hi @ovictorpa 

Can you specify which component(s) need refactoring? I am interested in helping with this issue.

Thanks!
