### ISSUE TITLE
Add new area "Save" button can not to press after adding area

### ISSUE THREAD

**Issue by isaac-aa** [OpenBeta/open-tacos#1036]
## Steps to Reproduce
1. Edit and existing area
2. Add a new area
3. Press save
4. Write another area name to add
5. The "Save" button is grey and can not be pressed again.

## Expected Behavior
I should be able to add more than one area in a row.

## Current Behavior
I can only create one, and have to reload the page to be able to add a second one.

## Browser & version
Mozilla Firefox 120.0.1

## Operating system
Linux 5.18.19-051819-generic

**Comment by vnugent** [comment]
@isaac-aa I deployed a fix.  Can you please verify?

**Comment by isaac-aa** [comment]
It now works :) thanks
