### ISSUE TITLE
Add Full screen control to map

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1039]
## Use case
I want to enter full screen mode to zoom in/out/pan the map using my mouse scroll wheel.  Currently, it's difficult to do so without holding down the Cmd/Window button.
- See the  https://docs.mapbox.com/mapbox-gl-js/example/fullscreen/
- How to do it in React map gl: https://visgl.github.io/react-map-gl/docs/api-reference/fullscreen-control
- Where to add it?  https://github.com/OpenBeta/open-tacos/blob/develop/src/components/area/areaMap.tsx#L70

**Comment by isaac-aa** [comment]
Can I be assigned to this issue? It will be nice for me to get used to the development environment :smiley:

**Comment by isaac-aa** [comment]
Hi! I started looking into this, but I have a (very tangential) doubt. Is there a reason why areaMap does not use BaseMap?
