### ISSUE TITLE
Remove area markers from map

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1058]
**What would you like to be able to do? Please describe.**
Crag markers are now included in the map layer.  There's no need to display individual crags.  We will introduce a way to click /hover on individual marker to get more info.  For now let's simplify the map.

### Todo 
Remove all markers https://github.com/OpenBeta/open-tacos/blob/develop/src/components/area/areaMap.tsx#L82-L109

**Comment by vnugent** [comment]
@Ali7040 want to take on this one?

**Comment by Ali7040** [comment]
@vnugent sure! I'm ready to take it on.

**Comment by Ali7040** [comment]
Please assign it to me.
