### ISSUE TITLE
Breadcrumbs should also show sibling areas

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1063]
**What would you like to be able to do? Please describe.**
When editing/exploring an area it's not easy to quickly navigate to sibling areas.  I want to be able to jump to a sibling area without having to go up to the parent.

**How important is this to you** (Please pick one)
- Nice-to-have

### Mockup
<img width="1325" alt="Screenshot 2024-01-06 at 1 47 36 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/5e880a7c-6b7f-487b-b2cf-fe974cc323e0">

**Comment by musoke** [comment]
It would be nice to show them in the map too

**Comment by vnugent** [comment]
### List sibling areas 
<img width="663" alt="Screenshot 2024-01-07 at 5 11 27 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/15d786e7-5d9a-4ef4-95a3-6e35d4cfadfb">

---

### Not easy to list all countries so just tell users to use the search box for now
<img width="568" alt="Screenshot 2024-01-07 at 5 12 18 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/c5216c87-42fe-43ca-bf06-e4cbe9e55878">

**Comment by btmccord** [comment]
What about adding a drop-down arrow link this so there is still the current easy navigation to the parent areas

![Screenshot 2024-01-07 at 18-25-10 Stone Free · 5 13a · Sport](https://github.com/OpenBeta/open-tacos/assets/24865286/3b422f1e-9233-43c3-aae7-b61c7953f511)

**Comment by vnugent** [comment]
> What about adding a drop-down arrow link this so there is still the current easy navigation to the parent areas

I thought about the same thing but the icon may be too small of a clicking surface area. In PR #1065 I took the easiest path, wrapping each item in a [HoverCard](https://www.radix-ui.com/primitives/docs/components/hover-card).  It works like the Profile hover card on Github.com, FB or Twitter.  The downside is hovering doesn't work on mobile.
