### ISSUE TITLE
Refactor/improve AreaPageContainer to support 2-column layout

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1066]
Both climb and area page use a 2-column layout defined by the following classes
- area-climb-page-summary
- area-climb-page-summary-left
- area-climb-page-summary-right

We should improve AreaPageContainer container to support left and right child component.

### Todo
- [ ] Improve AreaPageContainer to support a left and right child component
- [ ] Replace the divs in climb and area pages with the new component

- climb page: https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/climbs/%5Bid%5D.tsx
- area page: https://github.com/OpenBeta/open-tacos/blob/develop/src/app/area/%5B%5B...slug%5D%5D/page.tsx

**Comment by salgadopietrini** [comment]
Just confirming if this is still an open issue. Could I take on this one?
