### ISSUE TITLE
Enable click/hover on a crag drop pin and label

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1076]
**What would you like to be able to do? Please describe.**
As a user/contributor I want to click on a crag on the map to learn more about it and navigate to it.

**How important is this to you** (Please pick one)
- Important

### todo
- [x] Display neighbor crags (https://github.com/OpenBeta/openbeta-graphql/issues/377)
- [x] Show crag info on click/hover (#1076)

<img width="1302" alt="Screenshot 2024-01-13 at 7 38 17 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/0b11fffe-97fb-458b-8650-4128c76565a3">

**Comment by vnugent** [comment]
You can click on any of the square icons (boulder/crag/area) to see more info.  Will deal with mobile layout in a follow up PR.  We should promote the map to a top level page where users can explore pan/zoom and jump on a page.

---
<img width="875" alt="Screenshot 2024-01-18 at 12 27 46 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/d77f0f4a-9b43-4486-976b-ad18d25a88aa">

**Comment by musoke** [comment]
The clickable map is nice. It would be more obviously available if there was a tooltip or change in the pointer on hover.

**Comment by vnugent** [comment]
@musoke  PR #1081 makes it more obvious what you can click on.  Crag group boundaries are highlighted on hover and clickable.

Once backend issue https://github.com/OpenBeta/openbeta-graphql/issues/383 is done, we can display area description on the panel/tooltip.  Future PRs can address rich content, ex: discipline breakdown, photos, etc.

**Comment by musoke** [comment]
@vnugent , this is great!
