### ISSUE TITLE
Signup flow problems

### ISSUE THREAD

**Issue by heliodor** [OpenBeta/open-tacos#1082]
I just created an account:
- I received the verification email
- I clicked the verification link in the email
- I got taken to the "verification successful" screen at Auth0
- I clicked the "Back to OpenBeta button"
- I got a 404 page not found on the OpenBeta site (see screenshot)

What to fix:
- It looks like the `/auth/signin` endpoint is not being handled.
- The site should redirect to the url specified in the `iss` url param.

![Screenshot 2024-01-22 at 8 23 03 PM](https://github.com/OpenBeta/open-tacos/assets/395678/1f7e5d67-072b-416f-9d05-76d27784d4c3)

Suggested design improvement:

The button in the verification screen should be reconfigured to read "Continue to ..." instead of "Back to ..." Why? Because when I clicked the link in the email, I was not aware I was heading to a third party site. When I got to that screen, I didn't feel I was looking to "go back" but rather to "continue". Ideally, you can reconfigure this screen to instantly redirect to OpenBeta where the site can display a little notification at the top that reads "your email has been verified successfully". But frankly, the user shouldn't get to see that notification at all. The fact that the email address has been verified is of concern to OpenBeta more than to the user. Just continue to the site and let the user user the site.

![Screenshot 2024-01-22 at 8 29 03 PM](https://github.com/OpenBeta/open-tacos/assets/395678/f9ce69da-6f6b-4374-b581-f1c221854759)

**Comment by vnugent** [comment]
- [x] Correct login url to: `/login` (wrong value: ~~`/auth/signin`~~)
- [x] For email verification dialog, define redirectTo URL (previously empty) so that users will be redirect to openbeta.io automatically

Fortunately, these changes were made in Auth0 dashboard. No code change required.  Thanks @heliodor for reporting the issue.

@all-contributors add @heliodor for ideas & bug
