### ISSUE TITLE
Content width should be consistent from top to bottom of the page

### ISSUE THREAD

**Issue by heliodor** [OpenBeta/open-tacos#1096]
In the screenshot below, you can see the header is narrower than the rest of the page, and the banner and the map are full width. So there are three distinct widths to the content.

At the very least, the header should match the fixed max width of the content.

The full-width map can be excused as making full use of the space I suppose. Why not do the same with the pictures and use the full width?

Anyway, it's probably best to have a max width and stick to it. It will make the html/css simpler too.

![Screenshot 2024-02-13 at 10 19 53 AM](https://github.com/OpenBeta/open-tacos/assets/395678/2ae89e2d-c67e-4510-ad4b-6b40ca4d14a2)

**Comment by btmccord** [comment]
I think the map should stay full width, but I agree the other content should maintain a standard with.

**Comment by vnugent** [comment]
fixed in #1116

**Comment by heliodor** [comment]
What I meant: content width should be consistent *across all pages*!

In other words, there should be a template skeleton page from which all pages are rendered by filling in the "container" for the content. Things this template skeleton page should include:
header
footer
*content containe*r (full width, fixed width, whatever you like, but pick one)
a sidebar of some sort, if desired

**Comment by vnugent** [comment]
@heliodor I updated the landing page layout.  Except for individual climb pages and user profile, all other pages now use the same layout and margins.
