### ISSUE TITLE
Handle areas that don't exist

### ISSUE THREAD

**Issue by heliodor** [OpenBeta/open-tacos#1100]
After an area was deleted, I now see this server error instead of a 404 Not Found page:

https://openbeta.io/area/f92d68ca-1b6f-5bc7-8d1f-16b3961b3cce/puerto-rico

![Screenshot 2024-02-20 at 1 07 40 PM](https://github.com/OpenBeta/open-tacos/assets/395678/e1acbe31-b392-4fc1-8e9e-1a55204a16b4)

**Comment by heliodor** [comment]
Any url that has a UUID that does not exist in the database leads to the above error.
Any url that has other data instead of a UUID leads to a 404 page.

Try:
https://openbeta.io/area/f92d68ca-1b6f-5bc7-8d1f-16b3961b3cce/puerto-rico
https://openbeta.io/area/f92d68ca-1b6f-5bc7-8d1f-16b3961b3cce
https://openbeta.io/area/f92d68ca-1b6f-5bc7-8d1f-16b3961b3ccf
https://openbeta.io/area/f92d68ca-1b6f-5bc7-8d1f-16b3961b3ccd
https://openbeta.io/area/asdfasdf

**Comment by melissapthai** [comment]
Happy to take this on if no one else is. So just to confirm, if it's not a valid area, the page should return 404?

**Comment by vnugent** [comment]
> Happy to take this on if no one else is. So just to confirm, if it's not a valid area, the page should return 404?

Correct.  You can read more about Next 13 error handling https://nextjs.org/docs/app/api-reference/file-conventions/not-found

**Comment by melissapthai** [comment]
@vnugent thanks for approving my PR. I think this issue can be closed now, but lmk if there's anything I missed!

**Comment by vnugent** [comment]
@melissapthai thanks for the PR
@heliodor thanks for reporting the issue

I have a small followup PR that customizes the 404 page.  We can close this one.
