### ISSUE TITLE
bug: Page gets stuck on map when using scroll wheel

### ISSUE THREAD

**Issue by btmccord** [OpenBeta/open-tacos#1107]
### Current Behavior
When scrolling a area page with the mouse scroll wheel the page stops scrolling (up or down) once you reach the map. At this point using the mouse wheel results in a "use crtl+scroll to zoom the map" overlay on the map

### Expected Behavior
I should still be able to scroll up and down the page with the mouse wheel when the map is on screen.

### Reproduction
-Go to an area page
-Scroll with a mouse wheel down to the map
-Try to scroll back up or continue down

**Comment by vnugent** [comment]
The snapping css is probably defined incorrectly.

### Docs
- Mozilla https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_scroll_snap
- Tailwind: https://tailwindcss.com/docs/scroll-snap-type

### Code
- https://github.com/OpenBeta/open-tacos/blob/597f7fb66a2b13a1a74a37e56f9298f6e3cc9749/src/app/(default)/layout.tsx#L30
- https://github.com/OpenBeta/open-tacos/blob/597f7fb66a2b13a1a74a37e56f9298f6e3cc9749/src/app/(default)/components/ui/AreaPageContainer.tsx#L29

**Comment by btmccord** [comment]
This actually seems to only affect Firefox. Other browsers seem to ignore the snapping. What about just removing the snapping?

**Comment by vnugent** [comment]
> This actually seems to only affect Firefox. Other browsers seem to ignore the snapping. What about just removing the snapping?

Sure. We can live without it.
