### ISSUE TITLE
Map layers selector

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1108]
**What would you like to be able to do? Please describe.**
As a user I want to toggle between various map base layers (minimalist, outdoor, satelite) on https://openbeta.io/maps

**How important is this to you** (Please pick one)
- Nice-to-have

### Mockups
See https://maps.google.com for inspiration

<img width="448" alt="Screenshot 2024-02-29 at 10 42 42 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/1e1ac8d9-9d4c-421c-9eba-c824d23bcd45">

### Todos
- Develop a new LayerSwitcher component based on Radix UI [Hover card](https://www.radix-ui.com/primitives/docs/components/hover-card)
- Add it as a child component of Map in [GlobalMap.tsx](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/maps/GlobalMap.tsx#L132)
- Position the trigger control in the lower-left corner, slightly above the map scale.  Example of [absolute position on the map](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/maps/AreaInfoDrawer.tsx#L14)

**Comment by d-k-lippert** [comment]
@vnugent Anybody working on this yet? I would love to pick up this task.

**Comment by d-k-lippert** [comment]
@vnugent  @musoke 
shall we close this issue :)?

sorry that i forgot to use the "closes" action in the pr 🤦‍♂️

**Comment by musoke** [comment]
Done in #1118
