### ISSUE TITLE
"Remember" map center and zoom level

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1113]
**What would you like to be able to do? Please describe.**
As a user of the new global [climb map](https://openbeta.io/maps) I want to have a shareable URL that sets the map center and zoom level.

Example:
As you pan and zoom, the URL portion after `#` is used to track zoom level and center coordinates.  When I copy and open the complete URL in another browser window, the map is centered at the same location.
https://www.openstreetmap.org/#map=7/25.805/-102.393

**How important is this to you** (Please pick one)
- Important

**Comment by svkorepanov** [comment]
@vnugent @clintonlunn  Can I take over this task, since there is only stale PR?
