### ISSUE TITLE
Failing XSearch unit tests

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#1154]
There is a failing unit test that was caused by (#1152) ([XSearch Change](https://github.com/OpenBeta/open-tacos/pull/1152/files#diff-efbec9063b989104585be2af17db53335ddac7d083244a23594d664cd3318294)) by removing the searchPoi. The XSearch test is still expecting that geocoderLookupFn call to happen. 

## Screenshots
![image](https://github.com/OpenBeta/open-tacos/assets/24685932/1ad37345-cd93-491f-9f83-351b0cb73cb4)

## Expected Behavior

Tests pass after removing geocoderLookupFn expect

## Current Behavior
Failing unit test because geocoderlookup is nonexistent anymore

**Comment by clintonlunn** [comment]
I created this issue thinking it was just the failing tests (everything else passes locally, unit tests and build)...but I can't seem to get the build to pass once I push it to remote. @vnugent do you have any ideas of what could cause a failed build even if both unit tests and build passes locally?

**Comment by vnugent** [comment]
I think the failure was due to the staging API server timing out.  I've been trying to reduce our server expenses by switching to smaller VMs which caused some recent outages.

**Comment by clintonlunn** [comment]
@vnugent That makes sense! Thanks!
