### ISSUE TITLE
null shown in title on profile page

### ISSUE THREAD

**Issue by jeffpyke** [OpenBeta/open-tacos#1160]
## Steps to Reproduce

1. Navigate to profile page without display name e.g. https://openbeta.io/u/jeff

## Expected Behavior
Page title in browser tab should show "jeff (/u/jeff)"

## Current Behavior
Page title in browser tab shows "null (/u/jeff)"

## Browser & version
Firefox 127

## Operating system
MacOS 14.5

**Comment by clintonlunn** [comment]
@jeffpyke thanks for reporting, I took care of it. The issue was happening when the user had never entered a display name. Now, instead of null, it will be an empty string, showing only the information that is present.
