### ISSUE TITLE
Home page navigation improvement, climbs listed by state.

### ISSUE THREAD

**Issue by tedgeving** [OpenBeta/open-tacos#1177]
Add link from the top of the home page to the section where the routes are listed by state.  This is embarrassing but I did not realize that this section of the page existed. I ended up using the map as the primary way to find climbing areas instead of the ordered list. Overall the home pages seems to be lacking a cohesive navigation bar and or structure.  I've attached a comp for a possible quick fix.

- Nice-to-have

![Screenshot 2024-10-09 at 8 24 26 PM](https://github.com/user-attachments/assets/4b9dee73-0921-4933-ab6f-b4d272f1448b)

**Comment by AQIB-NAWAB** [comment]
@tedgeving I'm working on this issue 
I want to know the about the page
