### ISSUE TITLE
Image uploading failed (addMediaObjects call returns 500)

### ISSUE THREAD

**Issue by julianlam** [OpenBeta/open-tacos#1179]
## Steps to Reproduce

1. Attempted to upload a picture to [Bottle Glass Crag](https://openbeta.io/area/26bf3398-9219-5575-bf57-77032cceacfe/bottle-glass)
2. Upload modal displays and completes, the image is uploaded to Google storage, but the call to `addMediaObjects` fails

## Request

``` json
{"operationName":"addMediaObjects","variables":{"mediaList":[{"userUuid":"27339796-f8b5-48ed-b1bf-856dbd5289a2","mediaUrl":"/u/27339796-f8b5-48ed-b1bf-856dbd5289a2/NzfmkhwTMj.jpg","format":"jpeg","width":3024,"height":4032,"size":3182830,"entityTag":{"entityId":"26bf3398-9219-5575-bf57-77032cceacfe","entityType":1}}]},"query":"fragment EntityTagFields on EntityTag {\n  id\n  targetId\n  climbName\n  areaName\n  ancestors\n  type\n  topoData\n  __typename\n}\n\nfragment MediaWithTagsFields on MediaWithTags {\n  id\n  username\n  mediaUrl\n  width\n  height\n  uploadTime\n  entityTags {\n    ...EntityTagFields\n    __typename\n  }\n  __typename\n}\n\nmutation addMediaObjects($mediaList: [NewMediaObjectInput]) {\n  addMediaObjects(input: $mediaList) {\n    ...MediaWithTagsFields\n    __typename\n  }\n}"}
```

## Error response

``` json
{"errors":[{"message":"Context creation failed: An unexpected error has occurred.  Please notify us at support@openbeta.io.","extensions":{"code":"INTERNAL_SERVER_ERROR"}}]}
```

## Screenshots

![image](https://github.com/user-attachments/assets/f69bd8ce-8d38-4c81-b6a4-ea11caabbe25)

## Browser & version
Firefox 129.0.2-1.fc39

## Operating system
Linux Fedora

**Comment by julianlam** [comment]
Uploads fine on Chromium.

**Comment by musoke** [comment]
What happens if you log out and back in?

**Comment by julianlam** [comment]
@musoke Thanks, when I logged in again, the issue seems to no longer seems to occur. However, I did upload an image from a different spot (profile vs. area).

Nevertheless, if it happens again I will re-open.

**Comment by musoke** [comment]
I didn't remember the issue number right now, but there is one for certain
edits failing after being logged in for a while.  Something about sessions
expiring.

**Comment by musoke** [comment]
I think this is related to https://github.com/OpenBeta/open-tacos/issues/673
