### ISSUE TITLE
Nav overflow @~1120px width

### ISSUE THREAD

**Issue by CocoisBuggy** [OpenBeta/open-tacos#1201]
## Steps to Reproduce

1. Scale down screen until nav overflows

## Screenshots

![image](https://github.com/user-attachments/assets/b2820a50-77ce-4090-bd54-ac30944aeb0b)

## Expected Behavior

 Responsiveness could possibly be better specified

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

Firefox 

## Operating system
<--- Example:  MacOS 13.2.1 -->

nioxos

**Comment by luckyim0519** [comment]
Hola! I would like to work on this!

**Comment by CocoisBuggy** [comment]
Fantastic! Let me know if you have any questions

**Comment by vnugent** [comment]
Sorry @luckyim0519 it's been fixed by #1196 We find you another issue.

**Comment by luckyim0519** [comment]
That's fine! I'll browse the GitHub page and reach out when I find another
issue to ask for assignment!
