### ISSUE TITLE
New climbs page does not process markdown

### ISSUE THREAD

**Issue by julianlam** [OpenBeta/open-tacos#1217]
Noticed that the description (and perhaps other fields, but not tested) do not process markdown like the old `/climbs` page does.

## Observed 

![image](https://github.com/user-attachments/assets/c1b54b07-033d-4b80-b6ac-b137ff5bae79)

## Expected

![image](https://github.com/user-attachments/assets/33c08caf-9cc4-44c0-8067-703b0b8905e1)

**Comment by clintonlunn** [comment]
We need to wrap the react-markdown `<Markdown />` component around Description, Location, and Protection fields.
