### ISSUE TITLE
Copy Link button adds an extra '/' after base url

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#1230]
## Steps to Reproduce

1. Navigate to climb or area page (ex. https://openbeta.io/area/cce4ed2f-22de-50a0-8b1e-2193ea076d2b/hideout-boulders or https://openbeta.io/area/e1338408-c0d5-52ad-8cf7-62735953b440/coexist-boulder)
2. Click "Copy Link" button
3. Paste into a text box, observe the copied url looks like "https://openbeta.io//area/e1338408-c0d5-52ad-8cf7-62735953b440/coexist-boulder" or "https://openbeta.io//climb/315e9283-3a20-56cc-8893-ca9faf8d77fd/bermuda-triangle"  with an extra '/' after the `climb` or `area`)

## Expected Behavior

There should be a single '/' instead of '//'

## Current Behavior

There is '//' after the `climb` or `area` path.

## Notes
This doesn't actually break anything since the browser fixes this, but it doesn't look great. 

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

**Comment by AyalaFridman** [comment]
I want to work on this , can you assign me the task?

**Comment by clintonlunn** [comment]
@AyalaFridman sure thing. Let us know if you have any questions.

**Comment by AyalaFridman** [comment]
I get an error when I try to run the project.
The status code is 418 which as far as I know is the status code for "Net Free" which is the block I have,
Is there anything I can do about this?

**Comment by clintonlunn** [comment]
> I get an error when I try to run the project. The status code is 418 which as far as I know is the status code for "Net Free" which is the block I have, Is there anything I can do about this?

https://docs.openbeta.io/how-to-contribute/dev-onboarding

have you checked out our dev onboarding? We have first time contributor guide, and there are API keys we need to share with you for your .env.local file. 

In addition, we've got a discord server at https://discord.com/invite/a6vuuTQxS8 where we've got a variety of channels, including those looking for help.

**Comment by ShravaniRoy** [comment]
Hi @clintonlunn , I have setup the project and able to reproduce the issue. Would like to work on this. Could you assign issue to me?

**Comment by ShravaniRoy** [comment]
Removing the '/' from url is fixing the issue. Do you suggest any other approach?

**Comment by julianlam** [comment]
Open the PR first please.

**Comment by musoke** [comment]
This was assigned to @AyalaFridman just yesterday

**Comment by julianlam** [comment]
@AyalaFridman open the PR first please.
