### ISSUE TITLE
Add Sort button to sort climbs by Left-to-right or by grade

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#129]
Use case:  as a user I want to view climbs at a wall by grade.

By default we should sort climbs by their left-to-right index.  Optionally, users can also sort climbs by grade.

Notes:
- we generate climb cards here: https://github.com/OpenBeta/open-tacos/blob/develop/src/templates/leaf-area-page-md.js#L95
- a helper lib for comparing YDS is under development. For now don't worry about writing the sort/comparator yourself.

<img width="1255" alt="Screen Shot 2021-12-17 at 1 21 01 PM" src="https://user-images.githubusercontent.com/3805254/146538013-696ec569-c521-4afb-a7e2-c1cf502d41e6.png">

**Comment by gibboj** [comment]
@vnugent I'll take a look at this one next

**Comment by vnugent** [comment]
PR: https://github.com/OpenBeta/open-tacos/issues/129
