### ISSUE TITLE
Next JS list

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/open-tacos#159]
Parity
- [X] Add back heatmap w/ markers
- [X] Discuss Edit flow
- [X] Add back about / export pages
- [X] Fix font #158 

Changes
- [x] Have the US page show the biggest 10 crags.
- [x] Add (for now hardcoded) list of interesting crags, show with special markers on map
 ~~- [ ]Add starred to crag~~

**Comment by vnugent** [comment]
Fonts issue is fixed in https://github.com/OpenBeta/open-tacos/pull/158
