### ISSUE TITLE
Prototype layout for main index page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#174]

**Comment by gibboj** [comment]
Dev Prototype Info

https://www.figma.com/file/UkiHFfbJfRm5E9JpyJO4JQ/Components?node-id=432%3A2314

<img width="1431" alt="Screen Shot 2022-02-03 at 11 23 51" src="https://user-images.githubusercontent.com/2992272/152324504-fdbeca51-1a7c-4582-b640-ae3182f6c96f.png">

<img width="855" alt="Screen Shot 2022-02-03 at 11 26 30" src="https://user-images.githubusercontent.com/2992272/152324931-ac83d269-e354-42d8-8fd3-ec73dac6d5ad.png">

@vnugent Do we want this ticket to be more design prototype or dev prototype?

**Comment by vnugent** [comment]
we can start both

**Comment by vnugent** [comment]
we can start both

**Comment by vnugent** [comment]
[Figma Protoype](https://www.figma.com/proto/UkiHFfbJfRm5E9JpyJO4JQ/Components?node-id=669%3A545&scaling=min-zoom&page-id=504%3A242&starting-point-node-id=669%3A545)

**Comment by clintonlunn** [comment]
@vnugent this issue seems outdated, should it be closed?
