### ISSUE TITLE
Users can upload photos

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#176]
Possible photo providers:
1. ~~https://imgix.com/~~ can't search images by tags
2. https://cloudinary.com/
3. https://www.backblaze.com/
4. Raw Amazon S3 (pros: inexpensive, cons: no support for metadata)
5. Any other?

Subtasks:
- [x] Set up AWS S3
- [x] Link Imgix with S3.  Can't search images by tags :(
- [x] Evaluate Imagekit.io
- [x] Nextjs build can load photos from Imgix
- [x] Create a graphql mutation on the backend to link photo lat,lng to its photo id
- [x] Climb, area pages can display relevant photos from Imgix  https://github.com/OpenBeta/open-tacos/issues/306
- [x] Tag photos with areas/climbs
- [x] Setup Auth0 and/or [NextAuth](https://github.com/nextauthjs/next-auth-example) -->  #299 
- [x] Allow logged in user to upload photos

**Comment by clintonlunn** [comment]
possible provider for storage: https://www.backblaze.com/

**Comment by vnugent** [comment]
Screenshots https://github.com/OpenBeta/open-tacos/pull/333
