### ISSUE TITLE
Users can edit description

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#177]
- [ ] Investigate using 3rd party CMS vs rolling our own 
- [x] Add JWT/permission middleware to backend API
- [ ] Support basic edit operation

**Comment by zichongkao** [comment]
Seems like this has been completed: 
<img width="1164" alt="image" src="https://user-images.githubusercontent.com/3641356/235064020-7a39a4d2-626c-49f3-ad4b-0a3a2d20db45.png">
