### ISSUE TITLE
Upgrade Openverse API integration 

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/open-tacos#186]
* If we want to keep the openverse image sourcing we should upgrade to a real api integration w/ auth key so we don't get rate limited. 
* Could be also be built into the build process to fetch the image url? 
https://api.openverse.engineering/v1/#section/Introduction

**Comment by vnugent** [comment]
Yes, let's continue with this sourcing method until we have a way to store and get our own images.  Can we tune the query to get more climbing specific photos?  I'm seeing some non-climbing photos for Idaho and US.

**Comment by vnugent** [comment]
is it worth trying unsplash for full screen bg/heading photo? https://unsplash.com/developers?

**Comment by gibboj** [comment]
> Can we tune the query to get more climbing specific photos? I'm seeing some non-climbing photos for Idaho and US.
Yes, I think we should try to make it "more climbing specific" but then also have a fallback that is more broadly nature related and try to exclude humans
> is it worth trying unsplash for full screen bg/heading photo? https://unsplash.com/developers?
Sure I haven' tried searching that database but definitely worth a try

**Comment by vnugent** [comment]
Now that we support photo upload we can close this one.
