### ISSUE TITLE
Use external grade library

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#190]
Use our new grade library https://github.com/OpenBeta/sandbag

- `yarn add openbeta/sandbag`
- Delete [getScoreForGrade](https://github.com/OpenBeta/open-tacos/blob/develop/src/js/utils.ts#L117-L192)
- Replace references to `utils.getScoreForGrade` with the library function 

This issue is blocked by https://github.com/OpenBeta/sandbag/issues/7

**Comment by RishiKumarRay** [comment]
I Would like to do

**Comment by RishiKumarRay** [comment]
Replace references to utils.getScoreForGrade with the library function , what will the name of function to replace with?

**Comment by vnugent** [comment]
Sorry I just did a quick test and found an issue with how we incorrectly export `@openbeta/sandbag` module.  Can I notify you when https://github.com/OpenBeta/sandbag/issues/7 is fixed?

**Comment by RishiKumarRay** [comment]
yeah sure, please inform me , thanks

**Comment by vnugent** [comment]
fixed in https://github.com/OpenBeta/open-tacos/pull/204
