### ISSUE TITLE
Heatmap is no longer working 

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#195]
<img width="1241" alt="Screen Shot 2022-01-31 at 7 04 07 PM" src="https://user-images.githubusercontent.com/3805254/151897927-c770e7b6-1b43-4993-a874-4d561beebd93.png">

before 

<img width="437" alt="Screen Shot 2022-01-31 at 7 05 32 PM" src="https://user-images.githubusercontent.com/3805254/151898023-aa9b2ce9-46e0-4db8-919c-258d46a99c44.png">

**Comment by gibboj** [comment]
This is because the heat map and the cluster map are separate elements. You can switch it to the heat map.

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/open-tacos/issues/291
