### ISSUE TITLE
Discord Button Has No Margin

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/open-tacos#200]
Actual: Discord button isn't centered in the "closed" version of the header menu

Expected: Discord button should be centered vertically in the menu's close position, or at least not so close to the bottom 

<img width="278" alt="Screen Shot 2022-02-03 at 11 31 44" src="https://user-images.githubusercontent.com/2992272/152330200-f1d212ef-46e0-4336-b62f-79ecea60cd89.png">

**Comment by vnugent** [comment]
fixed in https://github.com/OpenBeta/open-tacos/pull/208
