### ISSUE TITLE
Climbing type icon not appearing on cluster map

### ISSUE THREAD

**Issue by gibboj** [OpenBeta/open-tacos#202]
Actual: 
<img width="857" alt="Screen Shot 2022-02-03 at 12 03 49" src="https://user-images.githubusercontent.com/2992272/152330923-8b28ee83-f4a0-4cb7-9fe0-ce6655a88fdb.png">
No circle icons appear on the map for the subareas. 
Expected: 
<img width="827" alt="Screen Shot 2022-02-03 at 12 04 35" src="https://user-images.githubusercontent.com/2992272/152330991-b5eda33f-a7e8-49c7-8dcd-3befc4a0eb94.png">
Areas should appear with a token on the map as a circle with the variety of climbing types

**Comment by gibboj** [comment]
I think this has to do with the gps data being used. Either the bounding box isn't being calculated properly or we don't have lat lng data. We should hide the map if its not providing anything. Or we should should have a fall back for lat long for larger areas that we can find on openmap (ie. I bet we can get a lat lng for arizona from open map)

**Comment by gibboj** [comment]
Maybe also we can get data from : https://ridb.recreation.gov/docs

**Comment by gibboj** [comment]
Used the children as backup GPS data. 
https://user-images.githubusercontent.com/2992272/152885744-b8914ae8-27c8-4d96-a226-59fcaefafd58.mov

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/open-tacos/issues/291
