### ISSUE TITLE
Upgrade @tailwindlabs/headlessui lib when available

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#246]
### Background: 
In [LeanPopover.tsx](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/ui/LeanPopver.tsx#L33
) the `onClick` should have been on Popover.Button.  But due to a bug, the button ignores user-defined onClick prop.

```javascript
        <div onClick={onApply}> 
          <Popover.Button className='text-primary-contrast bg-slate-800 rounded-md px-2 py-0.5'>
            {btnApplyLabel}
          </Popover.Button>
        </div>
```

To do:  
- [ ] Check to see whether  https://github.com/tailwindlabs/headlessui/pull/1265 has been released
- [ ] upgrade`@tailwindlabs/headlessui` lib to newer version 
- [ ] Remove outer div and add onClick to the button, ie, `<Popover.Button onClick={onApply} ...`

**Comment by tittaenalg** [comment]
Hey @vnugent, didn't see a way to assign this issue to myself, but created a pull request to address it: https://github.com/OpenBeta/open-tacos/pull/300

This is my first PR for open-tacos, so let me know if I missed any steps in the process.

**Comment by vnugent** [comment]
I think only project's team members with Write permission can assign issues.  I'm going to send you an invite.  Thanks for the PR!
