### ISSUE TITLE
Combine name search and crag search

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#255]
Currently we have 2 separate searches, Crag search and individual climb search.  We need to combine the 2 to simplify the UI.

### crag search near a city/well-known landmark

<img width="607" alt="Screen Shot 2022-04-04 at 12 14 36 PM" src="https://user-images.githubusercontent.com/3805254/161524199-e03b5112-e526-42ae-9ea0-5a1e2abb1ae5.png">

# climb search by name, FA, description
<img width="588" alt="Screen Shot 2022-04-04 at 12 18 03 PM" src="https://user-images.githubusercontent.com/3805254/161524214-98a54b0e-4ff6-4036-89f4-ae1b262d5691.png">

**Comment by vnugent** [comment]
I've built a skeleton and all the necessary backend plumbing https://tacos.openbeta.io?next=true

remaining todo's:

- [ ] design a suggestion screen
- [ ] write components for rendering suggested climbs, areas, fa, and cities
- [ ] figure out how to use hit score to highlight and organize suggestions

**Comment by CocoisBuggy** [comment]
This is currently working, we can revisit when the typesense collection for areas gets updated
