### ISSUE TITLE
What should we work on next?

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#256]
What do you want to see in OpenTacos?  
Please help us decide what to work on next.

Some ideas:

1.  Photo upload (#176)
2. Be able to bookmark climbs/search preferences (no ticket #)
3. Show me recommendations
4. More focus on maps (no ticket #)
5. Make it work better on mobile/tablet
6. ??

**Comment by clintonlunn** [comment]
I think most users (with or without an account) will interact with open-tacos on their phone, so catching up with any shortcomings on that front might give us a lot of benefit.

**Comment by vnugent** [comment]
I think we should also work on #255 (combining crag finder and climb search)

**Comment by clintonlunn** [comment]
@vnugent outdated and good to close? I think bookmarking would be covered in https://github.com/OpenBeta/open-tacos/issues/468
