### ISSUE TITLE
Account for all screen sizes

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#262]
Currently we do not account for larger screen sizes. The screens should be responsive to wider (2K/4K) screens. This seems to be present on most/all of the app. 

![image](https://user-images.githubusercontent.com/24685932/163241483-ed82ae4d-4e35-420b-8b2b-566c677a73c0.png)

![image](https://user-images.githubusercontent.com/24685932/163241689-5201eedb-cdf5-49bb-8db2-3abad4818504.png)

![image](https://user-images.githubusercontent.com/24685932/163241821-493d62fc-dd56-4a9c-a413-9062d00f853c.png)

**Comment by vnugent** [comment]
I'm making additional changes in PR #260.  I think we need to come up with a slightly different layout such as adding maps or additional content if we decide to support super large screens.

### 1.  Always full screen on Crag finder
<img width="1200" alt="Screen Shot 2022-04-17 at 9 01 22 PM" src="https://user-images.githubusercontent.com/3805254/163729226-494b01ff-4ea1-4dd9-bff4-861392dc260c.png">

---

### 2.  Index page and the rest are capped at `3xl` or 2560px.  Extra margins are set to black background
<img width="1304" alt="Screen Shot 2022-04-17 at 9 01 57 PM" src="https://user-images.githubusercontent.com/3805254/163729312-3386ecdd-0ea3-4887-b07d-a0524b05080f.png">

---
### 3.  Area/crag/climb pages 
Header/foot are capped at 3xl as mentioned above.  However, I decided to set the content to `max-w-screen-md` (768px) to make easier to read.

<img width="1296" alt="Screen Shot 2022-04-17 at 9 03 56 PM" src="https://user-images.githubusercontent.com/3805254/163729370-e1af69e4-60ba-417d-86ee-0fe600f1b2b5.png">

**Comment by clintonlunn** [comment]
@vnugent this issue has been fixed and is no longer relevant. Attaching screenshots from the large screen I reported this issue from previously.

![image](https://user-images.githubusercontent.com/24685932/210967772-83ee22fd-ceae-4713-886d-b3f341287046.png)
![image](https://user-images.githubusercontent.com/24685932/210968155-d42f22bd-7e22-4b69-aec9-5aad2e73c902.png)
![image](https://user-images.githubusercontent.com/24685932/210968233-60ab15c6-8cdf-44c2-8a84-14474981e9b0.png)
