### ISSUE TITLE
Search box should be wider on mobile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#264]
<img width="425" alt="Screen Shot 2022-04-15 at 12 34 21 AM" src="https://user-images.githubusercontent.com/3805254/163489004-6fd53f6f-855c-4cab-8ac4-70b3c4ef5740.png">

**Comment by clintonlunn** [comment]
@vnugent  should this be added to story #261?  I can also look into this if it's not something you're already working on.

**Comment by vnugent** [comment]
That’s right. Can you edit the issue and add it? If not I’ll add it when I have access to the laptop.
