### ISSUE TITLE
Filter bar too wide on mobile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#270]
<img width="325" alt="Screen Shot 2022-04-17 at 10 12 16 PM" src="https://user-images.githubusercontent.com/3805254/163731203-b20bb374-6e81-4698-9e2d-240c7ac96071.png">

**Comment by clintonlunn** [comment]
@vnugent could this be consolidated into a toggleable filter section?

**Comment by vnugent** [comment]
I've looked at other search-intensive site, and yes, they all do have a button that lets you access all filters.  However, they still place most important search options on the toolbar for quick access.  

A quick fix can be using Tailwind responsive class to shorten the button text to icon when screen < `sm` breakpoint.  

https://github.com/OpenBeta/open-tacos/blob/develop/src/components/ui/MobileFilterPopover.tsx#L21

```javascript
<button>

   <span className='sm:hidden'>{icon}</span><span className='hidden sm:inline'>{label}</span>

</button>
```
