### ISSUE TITLE
Design new layout for Climb and Crag page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#273]
### Use case: 

As a  sport (or trad, boulderer) climber I want to use the Crag page and the Climb page to find climbs within my level and discover similar, near by climbs.

- Crag page: https://tacos.openbeta.io/crag/3fc02dfc-def0-53d9-a53a-99025ea66a35
- Climb page: https://tacos.openbeta.io/climbs/770d8c36-62a2-5c06-9784-bd39ee1b62d5
Take into account mobile and very wide screens

**Comment by clintonlunn** [comment]
@vnugent fyi i updated this description to use valid urls now since there have been some updates since this issue was raised that broke the older url's

**Comment by clintonlunn** [comment]
@vnugent I would like to work on this if it's not currently being worked by @BeaulieuC, can we break out some of the tasks that would be necessary to complete this feature? To me, the task is a bit vague. 

Or I can take a different issue. Anything is fine with me :smile:

**Comment by vnugent** [comment]
I think @BeaulieuC put together a high level mockup/design somewhere on Figma

**Comment by clintonlunn** [comment]
> I think @BeaulieuC put together a high level mockup/design somewhere on Figma

Sounds good, I have not seen that!

**Comment by vnugent** [comment]
FYI Design https://www.figma.com/file/VBJaQSdUlIRMYeMnBENmn1/Wireframe-OpenBeta?node-id=0%3A1

**Comment by CocoisBuggy** [comment]
Doing some issue house-cleaning, I believe that this was closed with #332, although iterating on page design goes on forever and ever :muscle:
