### ISSUE TITLE
"Climbs For You" pie chart does not display correct information

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#276]
the pie chart in the "Climbs For You" section of a crag finder page does not seem to display correct information. 

![image](https://user-images.githubusercontent.com/24685932/164159070-e55552db-6bcc-4773-83c4-6d733d8f4bc1.png)

**Comment by vnugent** [comment]
Did PR https://github.com/OpenBeta/open-tacos/pull/274 fix this issue?

**Comment by clintonlunn** [comment]
> Did PR #274 fix this issue?

@vnugent  It did not. I need to read the [recharts](https://recharts.org/en-US/) documentation a little more to figure out how the drawing is happening.
