### ISSUE TITLE
Latest release: New area layout and photo sharing/tagging

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#277]
### Features/stories
- [x] https://github.com/OpenBeta/open-tacos/issues/273
- [x] https://github.com/OpenBeta/open-tacos/issues/291
- [ ] https://github.com/OpenBeta/open-tacos/issues/255
- [x] https://github.com/OpenBeta/open-tacos/issues/176
   - [x] https://github.com/OpenBeta/open-tacos/pull/299
   - [x] https://github.com/OpenBeta/open-tacos/pull/295
   - [x] https://github.com/OpenBeta/open-tacos/issues/319
   - [x] Logged-in users can edit their profile page https://github.com/OpenBeta/open-tacos/pull/331
   - [x] Logged-in users can upload photos https://github.com/OpenBeta/open-tacos/issues/305
- [ ] Customize Auth error pages https://github.com/OpenBeta/open-tacos/issues/318
- [x] https://github.com/OpenBeta/open-tacos/issues/306
   - [x] https://github.com/OpenBeta/openbeta-graphql/issues/74
- [x] https://github.com/OpenBeta/open-tacos/issues/248
- [x] https://github.com/OpenBeta/open-tacos/issues/304

### Bug fixes
- [x] https://github.com/OpenBeta/open-tacos/issues/275
- [x] https://github.com/OpenBeta/open-tacos/issues/270
- [x] https://github.com/OpenBeta/open-tacos/issues/264
- [x] https://github.com/OpenBeta/open-tacos/issues/276
- [x] https://github.com/OpenBeta/open-tacos/issues/290
- [x] https://github.com/OpenBeta/open-tacos/issues/308
- [x] https://github.com/OpenBeta/open-tacos/issues/289

### Need decision
- [ ] https://github.com/OpenBeta/open-tacos/issues/307

---

### Previous releases
- M2: https://github.com/OpenBeta/open-tacos/issues/178

**Comment by clintonlunn** [comment]
@vnugent if it's okay, i'd like to add #276 to this milestone for the bug fixes section

**Comment by vnugent** [comment]
# Area browser
<img width="1438" alt="area-explorer" src="https://user-images.githubusercontent.com/3805254/172345487-20e2ed3f-43d8-4331-94a2-28ef3b363863.png">

# Area browser with an area expanded
<img width="711" alt="Screen Shot 2022-06-07 at 11 26 21 AM" src="https://user-images.githubusercontent.com/3805254/172346248-d7282006-cd91-438f-9c1a-9538285cb945.png">

# New crag layout
<img width="939" alt="Screen Shot 2022-06-07 at 11 26 51 AM" src="https://user-images.githubusercontent.com/3805254/172346489-caa5a98e-b7c2-45b8-8720-334a66cc2356.png">

# New climb page layout

<img width="1010" alt="Screen Shot 2022-06-07 at 11 30 28 AM" src="https://user-images.githubusercontent.com/3805254/172347171-78d78a4c-3009-40aa-b16c-981b5159d945.png">


---

# User profile
<img width="321" alt="Screen Shot 2022-06-06 at 8 17 29 PM" src="https://user-images.githubusercontent.com/3805254/172345389-d83a9b4a-7430-47f4-8ea3-bcc6560f18bd.png">

### user profile desktop

<img width="1298" alt="Screen Shot 2022-06-06 at 8 16 46 PM" src="https://user-images.githubusercontent.com/3805254/172345405-f49c7e4c-b6d0-4447-ae37-c28d05412fef.png">
