### ISSUE TITLE
Backend changes break Explore section

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#280]
Explore section is now empty

<img width="295" alt="Screen Shot 2022-04-20 at 5 43 09 PM" src="https://user-images.githubusercontent.com/3805254/164270610-75c54062-47bf-4453-8125-c016c3c277d0.png">

**Comment by clintonlunn** [comment]
it seems like crag search is also not functioning. i am guessing it's a related issue
![image](https://user-images.githubusercontent.com/24685932/164287183-6506c4bc-8e44-4085-987a-a059fa190cd2.png)

**Comment by vnugent** [comment]
The crag finder search is working again after I redeployed everything.  The Explore section is still broken for sure.

**Comment by vnugent** [comment]
fixed in https://github.com/OpenBeta/open-tacos/issues/278
