### ISSUE TITLE
Sporadic error causing blank page (Maximum update depth exceeded)

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#289]
I encountered this error now and then.  I think it originated from the CragsMap component when I was viewing a highly populated area such as Boulder or Red Rock, and at the same time trying to zoom in and out when the component was still rendering.

https://reactjs.org/docs/error-decoder.html/?invariant=185

---

<img width="1127" alt="Screen Shot 2022-04-24 at 8 20 52 PM" src="https://user-images.githubusercontent.com/3805254/164991676-724c3d4d-c5e3-45b2-8f56-d856bd8dd60b.png">

**Comment by clintonlunn** [comment]
I am seeing this issue happen anytime that the user pans around the CragsMap

**Comment by vnugent** [comment]
A temporary fix could be wrapping the CragsMap component with an error boundary component https://www.npmjs.com/package/react-error-boundary

**Comment by CocoisBuggy** [comment]
After #311 I can't replicate this issue anymore

**Comment by vnugent** [comment]
Thanks.  I'm closing the issue.
