### ISSUE TITLE
Create a custom 404 page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#304]
Show users a custom 404 page 

https://nextjs.org/docs/advanced-features/custom-error-page

**Comment by CocoisBuggy** [comment]
Is there a spec for this? My instinct looks a little like this:
_(A quick optimization pass on those two image-planes would be needed)_

https://user-images.githubusercontent.com/64557383/168390913-7caf0d45-1b3a-406e-bf11-e8c65a744d24.mp4

Strictly speaking, this could be overly arbitrary... Was just the first thing that came to mind thematically

**Comment by vnugent** [comment]
Sorry I responded earlier but not sure it's not posted here.
Basically I wanted to say we don't have a spec.   I think the double layer scroll is really cool.  We should use it for a more visible page such as the [About](https://tacos.openbeta.io/about) page, and keep the 404 light and simple. What do you think?

**Comment by CocoisBuggy** [comment]
That's not a bad idea - I was thinking that this is probably overkill just for a 404 page

**Comment by CocoisBuggy** [comment]
That's not a bad idea - I was thinking that this is probably overkill just for a 404 page

**Comment by vnugent** [comment]
Fixed by https://github.com/OpenBeta/open-tacos/pull/312
