### ISSUE TITLE
Fix NextJS compilation warning re stylesheet

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#308]
How to reproduce
1. Follow instructions to set up the build locally
2. Run `yarn dev`

NextJS complains about incorrect placement the fonts import `/fonts/fonts.css` 

```
Do not add stylesheets using next/head (see <link rel="stylesheet"> tag with href="/fonts/fonts.css"). Use Document instead.
See more info here: https://nextjs.org/docs/messages/no-stylesheets-in-head-component
```

To do:
- Follow instructions provided by the link in the error message

**Comment by CocoisBuggy** [comment]
Ref doesn't seem necessary, as a parent component is already requiring fonts.css #309
