### ISSUE TITLE
names can be mangled in the breadcrumbs

### ISSUE THREAD

**Issue by atstp** [OpenBeta/open-tacos#346]
The [1-6-9 Boulder](https://tacos.openbeta.io/crag/dce84fc1-77f2-5760-80f0-6ac44d7d878e) is renamed to the "6-9 Boulder" in the breadcrumbs. 

[`sanitizeName`](https://github.com/OpenBeta/open-tacos/blob/a6292d268c9feb46aac1bde998f04cc720246c46/src/js/utils.ts#L98) seems to be the culprit

![1-6-9 Boulder becomes 6-9 Boulder](https://user-images.githubusercontent.com/5891072/172662951-f470c85c-69f7-495e-b334-bc8e78faedcf.png)

**Comment by vnugent** [comment]
Good catch!  We need to a systematic clean up effort on the data side to remove index from area names, `1.` `a.` , etc
