### ISSUE TITLE
Add photo timestamp to mobile view

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#370]
### Use case
As a user I want to know when a photo was taken.

For current behavior see  [my profile](https://tacos.openbeta.io/u/vietnguyen) in mobile view.

### Tips:
- UserMedia component: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/media/UserMedia.tsx#L64
- Convert `imageInfo.ctime`  to Date
- Display it when isDesktop is false
- Use a modern date util such as [date-fns](https://date-fns.org/) to format and display photo timestamp in human friendly format.  I think "x months ago or 3 weeks ago" for anything less than a year is easier to understand than May 2022.  Your thoughts?

<img width="309" alt="Screen Shot 2022-06-17 at 9 24 34 PM" src="https://user-images.githubusercontent.com/3805254/174401112-79d2c642-39bc-44e3-ad49-767ec0de2249.png">

**Comment by osaf96** [comment]
Hi, I would love to do this task. It would be first contribution and hope to learn and contribute more and more. please assign this to me. Thanks

**Comment by osaf96** [comment]
Thanks

**Comment by vnugent** [comment]
@osaf96 Unfortunately the gallery feature won't work for you in the dev env without Auth0 access key (see https://github.com/OpenBeta/open-tacos/issues/389).   Until we figure out a solution, would you see if there's another https://github.com/OpenBeta/open-tacos/labels/good%20first%20issue?

**Comment by osaf96** [comment]
oh ok, Let me know when you find the solution and when I can work on it.

**Comment by vnugent** [comment]
Hi @osaf96 
I'm just checking to see if you are still planning to work on this issue (I believe I have given you API keys via email)

**Comment by siman4457** [comment]
@vnugent I can pick this up once I have the API keys.

**Comment by vnugent** [comment]
> @vnugent I can pick this up once I have the API keys.
Thanks.  I've just sent you an email.
