### ISSUE TITLE
Reduce avatar size

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#382]
Reduce avatar size for users with existing avatar.

Profile component:  https://github.com/OpenBeta/open-tacos/blob/develop/src/components/users/PublicProfile.tsx

- Correct size: https://tacos.openbeta.io/u/vietnguyen
- Too large: https://tacos.openbeta.io/u/cocoisafraid 

<img width="1116" alt="Screen Shot 2022-06-21 at 11 29 17 PM" src="https://user-images.githubusercontent.com/3805254/174900622-79f3f523-cadb-4c2d-9b1c-1eac1c421701.png">

**Comment by xavier-kong** [comment]
@vnugent  Hi could I get this issue assigned to me? I would love to contribute!

**Comment by vnugent** [comment]
@xavier-kong I've jus assigned the issue to you.  Please send an email to viet at openbeta dot io for API keys.  

See this issue for more info: https://github.com/OpenBeta/open-tacos/issues/389
