### ISSUE TITLE
Update font files

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#385]
VCTR Mono has released a [new verson](https://www.vectrotype.com/)

To do:
1. Email viet at openbeta dot io for the latest  font files.zip
2. Delete existing files (except for fonts.css) in https://github.com/OpenBeta/open-tacos/tree/develop/public/fonts
3. Add new files and update fonts.css

**Comment by osaf96** [comment]
I can work on it in the meantime. Please assign it to me. @vnugent

**Comment by vnugent** [comment]
Fixed by #393
