### ISSUE TITLE
Create a full screen gallery for photo montage

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#386]
### Use case
As a user I want to click any photo on the montage to see larger version to learn more about the area.

Sample area:  
- https://tacos.openbeta.io/areas/ab48aed5-2e8d-54bb-b099-6140fe1f098f
- https://tacos.openbeta.io/areas/f166e672-4a52-56d3-94f1-14c876feb670

<img width="958" alt="Screen Shot 2022-06-22 at 8 20 19 PM" src="https://user-images.githubusercontent.com/3805254/175109309-2a6efe25-82d5-4b3d-91cc-be684ba40396.png">

**Comment by vnugent** [comment]
I just figured out how to create the "masonry" layout.  It's actually super easy to do with Tailwind.
- [CSS](https://github.com/OpenBeta/open-tacos/pull/400/files#diff-f598097aeddd7ccc99cf2212af8ec8be1dec6c2bfe4c191cc8a851db692aa1beR17)
- Screenshot https://github.com/OpenBeta/open-tacos/pull/400

**Comment by clintonlunn** [comment]
> I just figured out how to create the "masonry" layout. It's actually super easy to do with Tailwind.
> 
> * [CSS](https://github.com/OpenBeta/open-tacos/pull/400/files#diff-f598097aeddd7ccc99cf2212af8ec8be1dec6c2bfe4c191cc8a851db692aa1beR17)
> * Screenshot [Add new tab showing recent photos/tags #400](https://github.com/OpenBeta/open-tacos/pull/400)

That looks great! I'll definitely use this. I have a working modal with the photos but this will help to style them must better.

**Comment by vnugent** [comment]
@clintonlunn any progress on this one?

**Comment by clintonlunn** [comment]
@vnugent apologies, i had a working sample, but it seems to have gotten lost while i completed another issue. i need to rewrite what i had done before.
