### ISSUE TITLE
Support forward/backward photo navigation using arrow keys

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#387]
### Use case
In full screen mode I want to jump forward or backward using left and right arrow key.

Use react-hotkeys-hook

Tips:
- Next/Previous control: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/media/slideshow/NextPreviousControl.tsx
- Full screen viewer: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/media/slideshow/SlideViewer.tsx

### Screenshot

<img width="750" alt="Screen Shot 2022-06-14 at 5 43 29 PM" src="https://user-images.githubusercontent.com/3805254/175134512-8be410ae-2cda-4aed-89ca-4969e1e14c09.png">

**Comment by osaf96** [comment]
@vnugent  I would love to take a look at this. Please assign it to me.

**Comment by osaf96** [comment]
sorry, I got a bit busy for a few weeks. I'll quickly try to complete this issue this week hopefully.

**Comment by vnugent** [comment]
No worries.  I updated the original issue to include pointers to the 2 relevant components.

**Comment by tedgeving** [comment]
@vnugent @clinto 

I can take a look at this issue if it's still open.

**Comment by vnugent** [comment]
@tedgeving I assigned the issue to you then realized it has been implemented.  

If you're still interested in contributing a PR it would be great have a small follow up PR to show some instruction on the side bar.  Something like:

Keyboard shortcuts:  Previous [ ← ]    Next [  → ]
You can use DaisyUI [keyboard css classes](https://daisyui.com/components/kbd/) to style the button.

**Comment by tedgeving** [comment]
@vnugent I'll take a look at it. Thanks
