### ISSUE TITLE
User cannot upload photos using Ubuntu & Google Chrome

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#391]
There seems to be some issue with react-dropzone that prevents a user from being able to upload photos. Clicking on the photo uploader does not open the file explorer. As a workaround, the user can still drag and drop a photo into the photo uploading space.

I am using Ubuntu 21.10 and Google Chrome 100.0.4896.127.

**NOTE:** If I am using Firefox, I am able to use the file uploader to successfully upload an image.
This [example](https://react-dropzone.js.org/#section-opening-file-dialog-programmatically) on the react-dropzone documentation that uses a click handler is working for me. 

the open() function does not seem to be working here.

https://github.com/OpenBeta/open-tacos/blob/2cbb81727cef0d4990ede0467debb97a16185746/src/js/hooks/usePhotoUploader.ts#L57-L60

**Comment by clintonlunn** [comment]
I think this is a react-dropzone issue. The `accept` parameter here https://github.com/OpenBeta/open-tacos/blob/2cbb81727cef0d4990ede0467debb97a16185746/src/js/hooks/usePhotoUploader.ts#L53 seems to be what is breaking it, and removing this accept parameter allows the file upload box to open. I can reproduce my issue in this example (https://react-dropzone.js.org/#section-accepting-specific-file-types).

**Comment by vnugent** [comment]
Would something like this work?

```
accept: {
      'image/*': ['.jpeg', '.png']
    }
```

**Comment by clintonlunn** [comment]
> Would something like this work?
> 
> ```
> accept: {
>       'image/*': ['.jpeg', '.png']
>     }
> ```

@vnugent It does not. :-(

**Comment by CocoisBuggy** [comment]
I'm not sure if I have the same exact problem. I mostly use Firefox but I tried chrome (Ubuntu) and it just throws errors immediately when dropping photos

**Comment by CocoisBuggy** [comment]
I think this may have been fixed by #502 (Definitely fixed it for me on Ubuntu Chrome), I'll test in a few other environments when I have a chance

**Comment by clintonlunn** [comment]
@vnugent @CocoisBuggy, I no longer see this issue when trying to drag and drop images. Possibly good to close?
