### ISSUE TITLE
Sitemaps.xml

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#404]
### Use case
Need a sitemaps.xml and robots.txt file to improve SEO.  It can be a dynamic (based on src/pages) or a manual solution.

**Comment by Downster** [comment]
Alright, I wasn't exactly sure how to approach this as I haven't done it before but anyways here is the start of it. I pulled all of the UUID's from the GraphQL DB, and then parsed them into the url using python. This file will have to be split up I think, as most of what I have read says you can only submit sitemaps with up to 500 links. Is this along the lines of what you were looking for? 



`<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>https://tacos.openbeta.io/</loc>
  </url>
  <url>
    <loc>https://tacos.openbeta.io/areas/47667307-c0a0-5f50-873d-2a5c6d757fb2</loc>
  </url>
<url>
<loc>https://tacos.openbeta.io/areas/47667307-c0a0-5f50-873d-2a5c6d757fb2</loc>
</url>
<url>
<loc>https://tacos.openbeta.io/areas/60bc2823-f54f-59fa-9443-f61a87765009</loc>
</url>
<url>
<loc>https://tacos.openbeta.io/areas/c441f90b-7951-5ff1-b10a-e559fe24d2bc</loc>
</url>
<url>
<loc>https://tacos.openbeta.io/areas/82c2b699-d941-5829-b200-e118197a73ed</loc>
</url>
<url>
<loc>https://tacos.openbeta.io/areas/22d65b2e-22b9-5fbb-a014-9418306c3e60</loc>
</url>
<url>
<loc>https://tacos.openbeta.io/areas/0f897fc2-cf90-522b-8c46-80e5be3d3c7f</loc>
</url>`

If so, I can prettify it styling wise, and then start doing it on the other pages. How deep do you want me to go?

**Comment by vnugent** [comment]
The GraphQL query in the index page (src/pages/index.tsx) returns a list of large areas (Boulder, Co, red rocks, Indian creek…). Since that code runs on the server, can we generate the site maps file there?

We don’t have to list all the crags there are in the database.

**Comment by vnugent** [comment]
One interesting approach: taking advantage of NextJS server-side rendering to generate sitemaps.xml file:
https://cheatcode.co/tutorials/how-to-generate-a-dynamic-sitemap-with-next-js

For this PR I think we can just copy the GraphQL logic in src/pages/index.tsx to get the list of well-known areas.

**Comment by Downster** [comment]
Cool, sounds like a plan and thanks for that I'll have to check it out!
