### ISSUE TITLE
Add support email and social links to footer

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#408]
Update the the page footer component.

https://github.com/OpenBeta/open-tacos/blob/develop/src/components/layout.tsx#L31-L56

- [ ] Move `<footer ..>` tag out of layout.ts to its own file/component
- [ ] Add support email (support@openbeta.io)
- [ ] Add media links (see https://github.com/OpenBeta/openbeta.io/blob/develop/src/components/SocialIcons.js)

**Comment by xavier-kong** [comment]
Hi could I get this assigned to me? 

For the support email, should it be text or a mailto?

**Comment by vnugent** [comment]
> For the support email, should it be text or a mailto?
mailto please

**Comment by xavier-kong** [comment]
![image](https://user-images.githubusercontent.com/86543341/177787345-7a78c671-6fa2-45c0-97dc-d7809f353fcd.png)
![image](https://user-images.githubusercontent.com/86543341/177787429-363095ff-66f9-42a2-a045-7d519d84c844.png)

first screenshot min-width 1280px (xl)
second screenshot min-width 768px (md)

@vnugent  Does this work?

**Comment by vnugent** [comment]
Looks great.  A small requests:
- Change 'Support Email" to "Technical support" 
- Can you make OpenBeta in "A project by OpenBeta" an a tag linking to `https://openbeta.io`?
