### ISSUE TITLE
When tagging a climb, the autofill component goes off the page and you can't access all the results

### ISSUE THREAD

**Issue by Downster** [OpenBeta/open-tacos#427]
When uploading a picture to your profile, if you search for an area the search area renders off of the page, and you can't access the results that aren't currently on your screen. If you try to scroll down, the autocomplete box closes and you have to search again.

**Comment by vnugent** [comment]
We're using [Popper.js](https://popper.js.org/) for positioning the result panel.  I'm wondering if `preventOverflow` can keep the container within the page.

https://popper.js.org/docs/v2/modifiers/prevent-overflow/

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/open-tacos/pull/567
