### ISSUE TITLE
Prototype Area create, update, delete UI

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#429]

**Comment by CocoisBuggy** [comment]
I've put together a prototype in the figma prototypes doc for adding areas / climbs. I've tried to make it like a guided process, with a focus on having many opportunities to cut down on capturing duplicate entries. It's unproductive to have someone add an entry that already exists under a slightly different name, for example.

If it looks like a functional jumping off point, I'll build the components needed to make it work, and we can plug the API calls in as and when they become available

**Comment by vnugent** [comment]
Prototype figma file:  https://www.figma.com/file/Lvtb9bcbbN8zBexVSvaaFh/OpenBeta-Prototypes?node-id=416%3A751

**Comment by vnugent** [comment]
Nice start! Thanks.  I left a comment about showing separate hints for each selection (A generic area vs a crag/boulder).  Maybe a third option, "add a Country" (also indicating that it's a less common option, but it's essential to make it obvious before any areas can be added).  

FYI current Area mutation API:
- `addCountry(isoCode: countryCodeList)`
-  `addArea(name: string, parentId: uuid)` 
    I can add an optional `isLeaf: boolean` flag to indicate this is a crag/boulder.  Then the API will prevents new area(s) from specifying this area as its parent.
- `deleteArea(areaUuid: uuid)`
---
<img width="444" alt="Screen Shot 2022-07-31 at 1 24 33 PM" src="https://user-images.githubusercontent.com/3805254/182024035-86de2606-4520-4744-b04d-60a9f4fcaaef.png">

**Comment by CocoisBuggy** [comment]
48edbf39250923c38fdd706cdb42d996e77229a3, 111f040b857664a911befda66c6c11f24dff6665, and others have addressed this frameworking. Issue is stale - oops
