### ISSUE TITLE
User friendly message when upload image too large

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#436]
Display a user friendly message when upload image is too large (or when there's anything wrong with the upload)

### To do:
- [x] Write a simple popup alert based on https://www.radix-ui.com/docs/primitives/components/alert-dialog (we're phasing out `headless-ui`
- [x] handle client side error:  https://github.com/OpenBeta/open-tacos/blob/develop/src/js/hooks/usePhotoUploader.ts#L36
- [x] handle server side error: https://github.com/OpenBeta/open-tacos/blob/develop/src/js/hooks/usePhotoUploader.ts#L36

**Comment by CocoisBuggy** [comment]
Based on Radix or **using** Radix?

**Comment by vnugent** [comment]
> Based on Radix or **using** Radix?

Use Radix.  It's a headless component so we will need to style it.
