### ISSUE TITLE
Add section headers to search result pane

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#438]
Add 4 section headers to the search result panel

1. Climbs
2. Climbs near
3. Areas
4. First ascenionists

### Tips
- Place to add headers: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/search/XSearch.tsx#L33
- Use `text-primary` for color

<img width="645" alt="Screen Shot 2022-07-16 at 1 46 53 PM" src="https://user-images.githubusercontent.com/3805254/179353744-e09144d5-81ca-4302-a6d0-958ea955c647.png">

<img width="644" alt="Screen Shot 2022-07-16 at 1 50 55 PM" src="https://user-images.githubusercontent.com/3805254/179353752-2b260692-555c-4e4c-a925-4f334a6be772.png">

**Comment by Trevy05** [comment]
Can you assign me this issue? I would like to work on this.

**Comment by vnugent** [comment]
@Trevy05 another user has submitted a PR.  Let me identify a small task and assign the issue to you.

**Comment by Trevy05** [comment]
@vnugent that would be great, thank you!
