### ISSUE TITLE
Incorrect social media preview image

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#443]
### Issue
When sharing a photo link on social media, the preview image is randomly selected.  It should be the main one.

Example photo: https://tacos.openbeta.io/u/testy_blue_lamprey/NCzn79GHnt.png

- FB OpenGraph validator: https://developers.facebook.com/tools/debug

### Tips:
- First time contributor:  email viet at openbeta.io for API keys
- Open https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/p/%5B...slug%5D.tsx#L37
- Change `imageList: serverMediaList` --> `imageList: [serverMainMedia]`

**Comment by dlants** [comment]
When looking at the metadata for that page, there are multiple `og:image` tags. I think the intent of opengraph is that there is just one per page, and it seems like facebook will just pick the last one when deciding what to display.

See this stackoverflow for example:

https://stackoverflow.com/questions/13424780/facebook-multiple-ogimage-tags-which-is-default

**Comment by dlants** [comment]
or maybe it's just picking the highest res one?

**Comment by vnugent** [comment]
The intention was to allow the user to cycle through and select a different preview image when posting an **Area** or **Climb** page on FB, which hopefully gives FB audience the impression of us having "fresher" content.  

According to this [SO answer](https://stackoverflow.com/a/48859892), you can select from multiple images.

Sharing [Oregon page](https://tacos.openbeta.io/areas/5f05ed84-1a18-52d9-b8cf-77f8fd01e061) on my FB.  As you can see I'm supposed to be able to select a different image, but when clicking on the double-arrows, I couldn't select a different one.

---
<img width="480" alt="Screen Shot 2022-07-31 at 12 03 55 PM" src="https://user-images.githubusercontent.com/3805254/182021243-726a27d5-68e8-43cb-adbf-50dc29ea2dca.png">

---


In any case, my original bug description was misleading. This particular bug (which you have fixed in the PR, thank you!)  deals with the single image page (Example:  A photo of[ Illumination rock on Mt. Hood](https://open-tacos-git-fork-dlants-fix-443-openbeta-dev.vercel.app/p/vietnguyen/kKThkH6cc9.jpeg)), in which allowing multiple preview image doesn't make sense.
