### ISSUE TITLE
Photos on Popular page don't load

### ISSUE THREAD

**Issue by CocoisBuggy** [OpenBeta/open-tacos#444]
![image](https://github.com/OpenBeta/open-tacos/assets/64557383/1769ac07-03f4-48e8-8776-769e6ea5adf0)

Currently when a user navigates to the [popular](https://openbeta.io/?v=explore) panel on the homepage they are greeted with a slightly prototype-ish U.I that doesn't load media for areas that actually DO have tagged media.

## Suggestion

1. Correct these components so that they show actual media linked to areas. This need not be a carousel of all tagged media, but should ideally prioritize primary relationship rather than an inherited one through children. This requires legwork on the back-end so for the moment simply showing media will be sufficient.
2. Areas that have no media should either have a component with no image placeholder, or should not show at all. My opinion is that if the area is indeed a popular one, it will have some media in its children or as a primary relation.

**Comment by vnugent** [comment]
Is this still an issue?

**Comment by Ali7040** [comment]
Kindly assign this issue to me.

**Comment by Ali7040** [comment]
@vnugent What component should i look here for this issue? I'm a bit confused.
