### ISSUE TITLE
Footer in user profile page not at bottom of screen when user has less photos.

### ISSUE THREAD

**Issue by xavier-kong** [OpenBeta/open-tacos#462]
The footer could be at the bottom of the page rather than close to the center.

The u page 
https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/u/%5B...slug%5D.tsx 

calls the Layout component 
https://github.com/OpenBeta/open-tacos/blob/develop/src/components/layout.tsx 

which calls the Footer component 
https://github.com/OpenBeta/open-tacos/blob/develop/src/components/Footer.tsx

Reference image: the footer appears to be close to the center of the page. Could be an issue with handling users with few photos in profile. 
![image](https://user-images.githubusercontent.com/86543341/182157003-b0f225f7-6d8a-45b4-a3dd-118143351953.png)

**Comment by Hendriksn** [comment]
Hello! Is this still an issue? I would like to work on that!

**Comment by zichongkao** [comment]
Does not appear to be a problem anymore:
<img width="1263" alt="image" src="https://user-images.githubusercontent.com/3641356/235063382-cecb9418-a167-45d8-8db5-4cb50edbd212.png">


Can re-open if it still is!
