### ISSUE TITLE
Each main feed photo should be in a card

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#480]
[New Tags view](https://openbeta.io/?v=newTags)
On desktop we can hover over an image to click on either the tag or the image's author link.  On mobile we will need to put each photo in a card with header and footer (similar to FB, IG, Twitter feed) in order for users to interact with photos.

### To do: 
- [x] Create a generic photo card component with header, body, footer (in ./src/components/ui dir) (https://github.com/OpenBeta/open-tacos/issues/518)
- [ ] Wrap each photo in the new card component
- [ ] We can add actions/links to header and footer in a separate PR

<img width="311" alt="Screen Shot 2022-08-04 at 9 52 16 PM" src="https://user-images.githubusercontent.com/3805254/182940739-1ecad3a3-22c8-480c-8fdd-43c87c068a8c.png">

**Comment by osaf96** [comment]
@vnugent  I'm gonna look at this issue🙂

**Comment by siman4457** [comment]
@osaf96 Any updates on this? I'm willing to help or pick this up if needed.
