### ISSUE TITLE
Photos uploading from a route page should be tagged with that route by default

### ISSUE THREAD

**Issue by ygingras** [OpenBeta/open-tacos#499]
If I uploaded a photo from my profile, I don't expect any default tags, but if I uploading by following the link from a route page, I almost certainly mean to upload a photo of that route.

**Comment by CocoisBuggy** [comment]
I'll work on this, it seems like a reasonable behavior assumption for that button

**Comment by CocoisBuggy** [comment]
I have a fix for this that is halfway there

There is now a button that explicitly uploads-and-tags. I'll bring up the behavior of the top button at this weeks meeting and we can discuss how it should work.

Either way, this is a good piece of functionality to have started work on.

![image](https://user-images.githubusercontent.com/64557383/185947639-99aef45c-837d-4403-90da-21389d33b851.png)

#507 Will add this

**Comment by vnugent** [comment]
Fixed in PR #619 

Instead of adding a new Upload button, I added additional logic to the current button to determine the current page from Next useRouter() hook and add a tag accordingly.
