### ISSUE TITLE
Areas should also have photos

### ISSUE THREAD

**Issue by ygingras** [OpenBeta/open-tacos#500]
We can currently attach photos to routes, but photos can also relate to whole areas. 

Example use cases:
- overview of the cliff;
- map showing where to park;
- distinct features along the approach trail.

**Comment by CocoisBuggy** [comment]
Agreed, I'm on it

**Comment by vnugent** [comment]
I'm adding an Area-only search widget in PR https://github.com/OpenBeta/open-tacos/pull/506 that you can reuse for this.

**Comment by vnugent** [comment]
you can now tag an area

<img width="190" alt="Screen Shot 2022-11-22 at 8 17 36 PM" src="https://user-images.githubusercontent.com/3805254/203641668-94ffc228-b92f-47ce-9e2b-5cff323e8712.png">

---

<img width="293" alt="Screen Shot 2022-11-22 at 8 18 33 PM" src="https://user-images.githubusercontent.com/3805254/203641744-639f1c41-c2fa-4089-911e-2b6ec00b48ae.png">

**Comment by ygingras** [comment]
Sweet! Great work, team! I love the pic of The Great Game: such a stellar technical layback that requires very precise smearing. That picture captures the intensity of the challenge beautifully.

**Comment by vnugent** [comment]
> Sweet! Great work, team! I love the pic of The Great Game: such a stellar technical layback that requires very precise smearing. That picture captures the intensity of the challenge beautifully.

The Great Game is one of my all time favorites.

Related issue https://github.com/OpenBeta/open-tacos/issues/499 will be addressed in a separate PR
