### ISSUE TITLE
Create a Twitter/IG style card component

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#518]
Needed by https://github.com/OpenBeta/open-tacos/issues/480
- [x] Mobile first
- [x] Based on Daisy UI [Card](https://daisyui.com/components/card/)
- [x] contains a header, body and footer
- [x] 1 simple unit test

<img width="1118" alt="Screen Shot 2022-09-18 at 11 28 17 AM" src="https://user-images.githubusercontent.com/3805254/190895522-940032c6-e6c7-42c2-a7d4-0a7ba8857764.png">

**Comment by siman4457** [comment]
I can pick this up

**Comment by vnugent** [comment]
@siman4457 thanks for taking care of this!
