### ISSUE TITLE
Remove duplicate financial donors

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#547]
### Issue
It seems like when someone contributes multiple times to different tiers, their data is shown for each tier.
- Go to https://openbeta.io/?v=backers
- Adelore and Alex appear 2x 

### To do

In [FinancialBackers.tsx](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/home/FinancialBackers.tsx#L15) remove duplicates using **underscore** [uniq](https://underscorejs.org/#uniq) (lib already included in the project) or something equivalent.

**Comment by Theakayuki** [comment]
Created fix with underscore like recommended, and setup pull request.

**Comment by siman4457** [comment]
UI could also use an update on mobile. Seems to be too many cards per row and too much text per card. Consider reducing font size on mobile. ![image](https://user-images.githubusercontent.com/28658492/192810960-0c38a16d-fd41-44a7-b624-b5e84423696f.png)

**Comment by vnugent** [comment]
@siman4457 can you please create an issue?
