### ISSUE TITLE
Toolbar too wide for mobile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#552]
PR https://github.com/OpenBeta/open-tacos/pull/545 introduces an additional icon (Backers) to the toolbar making it too wide to fit in mobile screen size Small (375px).

Short term fix:  Reduce padding between icons

---

<img width="286" alt="Screen Shot 2022-09-27 at 4 15 46 PM" src="https://user-images.githubusercontent.com/3805254/192551767-e5013805-c7c4-420b-8f0d-1bb7318a8a72.png">

**Comment by busbyk** [comment]
Just used this tiny task as motivation to actually get the project pulled down and running locally and get familiar with the frontend project.
