### ISSUE TITLE
Use financial donor account id to ensure unique 

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#555]
Related issue #547 

Currently we're using name as a key to ensure uniqueness.  Short term fix: https://github.com/OpenBeta/open-tacos/pull/548

A better approach would be grouping the donor list by account id.

### Todo
- Insert a new line with id above name: https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/index.tsx#L228
- Declare id type: id: string https://github.com/OpenBeta/open-tacos/blob/develop/src/js/types.ts#L269
- update `uniq` function to use id instead of name https://github.com/OpenBeta/open-tacos/blob/develop/src/components/home/FinancialBackers.tsx#L10

```javascript
  const uniqDonors = uniq(donors, (donor) => donor.account.id) // Using the underscore library to get unique donors, based on their name
```

**Comment by Balastrong** [comment]
Thank you for all the guidance, I did the changes as indicated in your Todo list :)

Just one detail, the second code pointer is to line `269` but I think it was supposed to be line `279`, right?
https://github.com/OpenBeta/open-tacos/blob/fd607cfb449b852b973bead00612911ebd74c297/src/js/types.ts#L263-L282

**Comment by vnugent** [comment]
@Balastrong you are right. Thank you for the PR!
