### ISSUE TITLE
Update UI for financial donors page

### ISSUE THREAD

**Issue by siman4457** [OpenBeta/open-tacos#565]
UI could also use an update on mobile. Seems to be too many cards per row and too much text per card. Consider reducing font size on mobile. ![image](https://user-images.githubusercontent.com/28658492/192810960-0c38a16d-fd41-44a7-b624-b5e84423696f.png)

__Originally posted by @siman4457 in https://github.com/OpenBeta/open-tacos/issues/547#issuecomment-1261029347__

**Comment by su-mit** [comment]
Hi @siman4457, I would like to work on this issue

**Comment by vnugent** [comment]
@su-mit I've assigned the issue to you.

**Comment by vnugent** [comment]
@su-mit Please let us know if you have any questions.

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/open-tacos/pull/625
