### ISSUE TITLE
Climb tag search box broken

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#566]
Previously the search box displays a list of suggestions as you start typing.  Now nothing is showing up.

<img width="311" alt="Screen Shot 2022-09-30 at 7 44 13 PM" src="https://user-images.githubusercontent.com/3805254/193424768-b2c64933-777a-45f1-b6b4-552142ffcf8d.png">

**Comment by osaf96** [comment]
Hi @vnugent I can give it a try. oh you are working on it. got it

**Comment by vnugent** [comment]
Hi @osaf96 I've already fixed this bug in PR https://github.com/OpenBeta/open-tacos/pull/567

**Comment by osaf96** [comment]
@vnugent yup! Got it
