### ISSUE TITLE
A crude way to view all my ticks

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#576]
#525 
### Use case
As a former MP user I was able to import my ticks without seeing any errors.  However, there isn't an immediate way to views all my ticks.  It would be nice to have a super simple page listing all my ticks.

<img width="281" alt="Screen Shot 2022-10-13 at 5 46 06 PM" src="https://user-images.githubusercontent.com/3805254/195724445-68ef595e-9b73-4c26-8c00-4ab50004af9f.png">

**Comment by Downster** [comment]
I'll hop on this in the coming weeks. Thinking some data-viz for grades etc... and an ability to share to social medial would be cool!

**Comment by vnugent** [comment]
PR #577 
I added a simple tick list page.  Let's close this ticket and create different ones for visualization/social media sharing.
