### ISSUE TITLE
Don't show Import Ticks button unless I'm viewing my own profile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#578]
This issue tracker is **ONLY** used for reporting bugs!

## Expected Behavior
Don't show Import ticks button unless I'm viewing my profile

## Current Behavior
When I look at someone else's profile I see the Import ticks button next to their name

screenshot: I'm not the logged in user

---
<img width="281" alt="Screen Shot 2022-10-22 at 3 12 47 PM" src="https://user-images.githubusercontent.com/3805254/197360736-deedc6d9-2a0d-4796-8419-208a11e77882.png">

## Possible Solution
Check to see if the logged user is viewing their own profile

## Steps to Reproduce
https://openbeta.io/u/ntgong90

**Comment by Shaglock** [comment]
Hello, @vnugent I tried to fix this as part of hacktoberfest, could you please add the label here and take a look at PR that I opened? https://github.com/OpenBeta/open-tacos/pull/588
