### ISSUE TITLE
Move Import ticks to a new location to preserve mobile layout

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#580]
When a user nick name is very long, the import button causing the screen to expand beyond the screen width on mobile devices.

### To do:
- [ ] Move the Import button component next to the View ticks link. [Profile component](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/users/PublicProfile.tsx#L58)

See also #578 
--- 
<img width="282" alt="Screen Shot 2022-10-24 at 11 00 10 AM" src="https://user-images.githubusercontent.com/3805254/197839216-cef43029-5bbc-4d9e-ae44-e55b88e6172e.png">

**Comment by Shaglock** [comment]
<img width="363" alt="image" src="https://user-images.githubusercontent.com/15055321/199093406-fdfa11e5-0a4d-46b0-be88-37794bff9bf2.png">
Even if we move the buttons there is also a problem with the buttons in the header.  But that's below 367 pixels width or so. Do you aim to support such screens?

Also, even if we move the buttons somewhere, the problem with the nickname stays... It probably can be very long and that will still cause issues on low width screen.

<img width="403" alt="image" src="https://user-images.githubusercontent.com/15055321/199094711-b1f4f9b1-20d7-4234-a55d-30c2716d453c.png">

 What's the desired/best solution to this?

**Comment by vnugent** [comment]
Minimum 320px.  I thought we enforce max length on user name?

**Comment by Shaglock** [comment]
> Minimum 320px. 

In that case there are 2 issues:
1. hamburger menu 
2. Long user name

> I thought we enforce max length on user name?
Do you mean you enforce max length on backend? Since I am new to this project I don't know much details :)

**Comment by vnugent** [comment]
You're right that many mobile components exceed the 320px width.

For long user name can we use a JS or CSS solution such as [Tailwind truncate](https://tailwindcss.com/docs/text-overflow#truncate)?

We can fix the menu in a separate PR.

**Comment by Shaglock** [comment]
Hey @vnugent so did #596 fix this issue or its still there? Maybe we can close this issue

**Comment by vnugent** [comment]
Yes, it's been fixed.  Thank you.
