### ISSUE TITLE
Change text color on the "Climbs Near" view

### ISSUE THREAD

**Issue by siman4457** [OpenBeta/open-tacos#584]
## Expected Behavior
Easily be able to read filters.

## Current Behavior
The text color is almost the same as the background color for filters.
<img width="618" alt="Screen Shot 2022-10-28 at 1 00 28 AM" src="https://user-images.githubusercontent.com/28658492/198514592-fd80e93d-ad6f-4d36-a519-0e663e92fe1f.png">

## Possible Solution
Either add a background color to the filter buttons or change the text color of the filter buttons.

## Steps to Reproduce
https://openbeta.io/finder?shortName=Austin&placeId=place.15042796&center=-97.7437,30.271129

**Comment by Sandi2212** [comment]
please assign this to me

**Comment by Shaglock** [comment]
Hello, @vnugent  I tried to fix this as part of hacktoberfest, could you please add the label here and take a look at PR that I opened? #587
