### ISSUE TITLE
List other countries besides USA

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#585]
## Expected Behavior
I'm testing area edit #496 and want an easy way to navigate to different countries besides the US

## Current Behavior
Currently there isn't an easy way to browse other countries besides the US

## Possible Solution
<img width="978" alt="Screen Shot 2022-10-28 at 10 33 18 AM" src="https://user-images.githubusercontent.com/3805254/198733392-3a83beee-767f-4465-bd45-c40e741ad3c4.png">

**Comment by clintonlunn** [comment]
@vnugent the screenshot didn't load correctly

**Comment by vnugent** [comment]
fixed!
