### ISSUE TITLE
Shorten latitude & longitude

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#599]
### Issue
Latitude & longitude are shown with all of their significant digits.

Example:
44.36890442356387,  -121.13926266934996
https://openbeta.io/areas/f3c655b6-9c95-597f-aaa6-fd7d8a4865ec

### To do

Use `toFix(5)` ([docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed)) to shorten lat & lng in
- src/pages/areas/[id].tsx
- src/pages/crag/[id].tsx

<img width="240" alt="Screen Shot 2022-11-06 at 7 58 48 PM" src="https://user-images.githubusercontent.com/3805254/200189786-715d9d21-3b77-4a15-9495-d58e760a2287.png">

**Comment by christophermorin** [comment]
Hello. I'd like to take a crack at this. I'll send a PR up, hopefully it's what you are looking for.
