### ISSUE TITLE
User profile not found

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#617]
## Expected Behavior
When I change my user name I should be able to view my profile

## Current Behavior
http 404 

## Possible Solution
Take a look at user name update logic.  I should update user name in Auth0 and Sirv

**Comment by vnugent** [comment]
related https://github.com/OpenBeta/open-tacos/issues/617

**Comment by siman4457** [comment]
I wasn't able to reproduce this issue.

**Comment by vnugent** [comment]
Fixed by https://github.com/OpenBeta/open-tacos/pull/838
