### ISSUE TITLE
MP import feature only shows 3

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#631]
## Expected Behavior
MP user: https://www.mountainproject.com/user/200492669/andre-chiquito
OB profile: https://openbeta.io/u/all_terrain_human

The user has over 400 ticks but it seems only 3 are imported/shown

cc @Downster

**Comment by musoke** [comment]
I think I understand what happened: the importer couldn't handle the same route appearing twice in a row.  

The same happened to my attempted import.  The first 32 routes were fine, but the rest are missing.  The 33rd tick in my logbook is of the same route as the 32nd.

Judging by the dates on this issue and their logbook, these were the three most recent routes at the time of the attempted import:
```
Left Of Time
The Twins Right
Hardman
Hardman
Mr. Aidman's Free
Black Hole
```

These are the three ticks imported successfully:
```
The Twins Right
Hardman
Left Of Time
```
It seems to have failed when it saw the second Hardman.

**Comment by musoke** [comment]
I suspect that this is related to the error message that appears when attempting to log multiple ticks on the same day through the web interface. 

![image](https://user-images.githubusercontent.com/16665084/224570280-9ad42621-4391-4f85-bcc3-25558ddf40a8.png)


 Is there a reason for that being disallowed?  I often do a climb more than once in a day.

**Comment by vnugent** [comment]
> Is there a reason for that being disallowed? I often do a climb more than once in a day.

I think due to date string being used as the unique constraint: https://github.com/OpenBeta/openbeta-graphql/issues/175

**Comment by musoke** [comment]
Ah!  Makes sense.  Not sure I have the skills to fix it.

**Comment by musoke** [comment]
In any case, the importer should probably attempt to continue after encountering an error with individual  ticks.

**Comment by milbmr** [comment]
I want to work at this issue but i need API keys to access users Profile.

**Comment by vnugent** [comment]
> I want to work at this issue but i need API keys to access users Profile.

@milbmr 
can you please send me an email: viet at openbeta dot io

**Comment by musoke** [comment]
I have another datapoint: 

I imported the following log book:
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/624f07d5-164b-4ad6-9cd6-edeb053965d7)
It has two pairs out routes, each ticked twice on one day.  
1. The first pair has different style.
2. The second pair has the same style.

Here's the list of ticks as reported by https://stg-api.openbeta.io:
```
{
  "data": {
    "userTicks": [
      {
        "_id": "64afe8808827f07ef7253506",
        "userId": "c26b3c91-bb05-42a9-8f8c-b2209c55781b",
        "name": "Lemonade",
        "notes": "",
        "climbId": "6cf437fa-027c-52ba-b0f0-7eda58fa4a2b",
        "style": "N/A",
        "attemptType": "N/A",
        "dateClimbed": 1682899200000,
        "grade": "V5",
        "source": "MP"
      },
      {
        "_id": "64afe8808827f07ef7253507",
        "userId": "c26b3c91-bb05-42a9-8f8c-b2209c55781b",
        "name": "Lemonade",
        "notes": "",
        "climbId": "6cf437fa-027c-52ba-b0f0-7eda58fa4a2b",
        "style": "Attempt",
        "attemptType": "Attempt",
        "dateClimbed": 1682899200000,
        "grade": "V5",
        "source": "MP"
      },
      {
        "_id": "64afe8808827f07ef7253508",
        "userId": "c26b3c91-bb05-42a9-8f8c-b2209c55781b",
        "name": "Cream Cheese",
        "notes": "",
        "climbId": "921a5290-a42e-5aec-8c67-f8d9fe4b01c8",
        "style": "Flash",
        "attemptType": "Flash",
        "dateClimbed": 1680307200000,
        "grade": "V6",
        "source": "MP"
      }
    ]
  }
}
```

The first pair imports successfully, the second does not. 
It would seem that it is the combination of same day and style that fails.  Differentiating by "notes" does not help.

**Comment by musoke** [comment]
I get this error when doing the import on a local dev open-tacos instance with the prod backend.

```
Unhandled Runtime Error

ApolloError: E11000 duplicate key error collection: openbeta.ticks index: climbId_1_dateClimbed_1_style_1_userId_1_source_1 dup key: { climbId: "921a5290-a42e-5aec-8c67-f8d9fe4b01c8", dateClimbed: new Date(1680321600000), style: "Flash", userId: "c26b3c91-bb05-42a9-8f8c-b2209c55781b", source: "MP" }


Call Stack
ApolloError
node_modules/@apollo/client/errors/index.js (26:0)
QueryManager.prototype.mutate/</</</<
node_modules/@apollo/client/core/QueryManager.js (97:0)
both
node_modules/@apollo/client/utilities/observables/asyncMap.js (16:45)
then/<
node_modules/@apollo/client/utilities/observables/asyncMap.js (9:56)
then
node_modules/@apollo/client/utilities/observables/asyncMap.js (9:0)
makeCallback/<
node_modules/@apollo/client/utilities/observables/asyncMap.js (17:0)
notifySubscription
node_modules/zen-observable-ts/module.js (132:0)
onNotify
node_modules/zen-observable-ts/module.js (176:0)
next
node_modules/zen-observable-ts/module.js (225:0)
iterateObserversSafely/<
node_modules/@apollo/client/utilities/observables/iteration.js (4:49)
iterateObserversSafely
node_modules/@apollo/client/utilities/observables/iteration.js (4:0)
next
node_modules/@apollo/client/utilities/observables/Concast.js (25:42)
notifySubscription
node_modules/zen-observable-ts/module.js (132:0)
onNotify
node_modules/zen-observable-ts/module.js (176:0)
next
node_modules/zen-observable-ts/module.js (225:0)
next
node_modules/@apollo/client/link/error/index.js (29:0)
notifySubscription
node_modules/zen-observable-ts/module.js (132:0)
onNotify
node_modules/zen-observable-ts/module.js (176:0)
next
node_modules/zen-observable-ts/module.js (225:0)
readJsonBody/<
node_modules/@apollo/client/link/http/parseAndCheckHttpResponse.js (144:0)
```

**Comment by vnugent** [comment]
I see what's going on now.  The database has a unique constraint on climb, date, style, user, source to prevent the same tick from being imported multiple times.  We can think of some other way to address re-import use case.

```javascript
TickSchema.index({ climbId: 1, dateClimbed: 1, style: 1, userId: 1, source: 1 }, { unique: true })
```
https://github.com/OpenBeta/openbeta-graphql/blob/develop/src/db/TickSchema.ts#L27

**Comment by musoke** [comment]
I think the current implementation deletes previously imported ticks before doing the new import, so one can probably disable this addition check for now? Double check this.

**Comment by vnugent** [comment]
You're right.  The import deletes all previous ones.  We can change the indexes to something like this:

```javascript
TickSchema.index({ userId: 1 }) // ticksByUser()
TickSchema.index({ climbId: 1, userId: 1 }) // for ticksByUserIdAndClimb()
```
