### ISSUE TITLE
A page with lots of pictures (i.e. top level USA area) will return a 404

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#646]
bug was introduced in https://github.com/OpenBeta/open-tacos/pull/642 in this [commit](https://github.com/OpenBeta/open-tacos/pull/642/commits/c54de85c7769b3354efca27a3b8bbe5f6306cbb5) as a way to bring in image dimensions for displaying well in the PhotoGalleryModal

## Expected Behavior
A page that contains lots of pictures will not have any issues loading.

## Current Behavior
A page that contains lots of pictures fails to load with a 404
![image](https://user-images.githubusercontent.com/24685932/210975637-391ee79c-98c7-4e53-bbf9-a70f30cfec92.png)
sirv response
![image](https://user-images.githubusercontent.com/24685932/210975791-9b50de27-acb7-4c18-bcd9-177c53900056.png)
example of failed query
![image](https://user-images.githubusercontent.com/24685932/210975925-dcbb4c04-d9cf-42e9-9326-295549180d7b.png)

## Possible Solution
This issue is being cause by the sirv query being too long (see [Sirv Rest API: Search Files documentation website](https://apidocs.sirv.com/#search-files)  "maxLength": 1024 (characters))

We could 
- remove the getImagesByFileName() from crag, climbs, and areas pages and bring in images with dimension metadata already attached (**NOTE:** needs backend work/tickets)
  - [https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/areas/%5Bid%5D.tsx#L191-L196](areas)
  - [https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/climbs/%5Bid%5D.tsx#L358-L363](climbs)
  - [https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/crag/%5Bid%5D.tsx#L177-L182](crag)
- simple workaround provided by sirv support (TBD)

## Steps to Reproduce

1. Navigate to [https://openbeta.io/areas/1db1e8ba-a40e-587c-88a4-64f5ea814b8e](https://openbeta.io/areas/1db1e8ba-a40e-587c-88a4-64f5ea814b8e), this is USA area
2. View that a 404 is returned
3. If the user has access, view logs showing the sirv exception on https://vercel.com/openbeta-dev/open-tacos

**Comment by vnugent** [comment]
I created an actionable ticket https://github.com/OpenBeta/open-tacos/issues/659 to fix this,
