### ISSUE TITLE
New Tags: Link photo to tag

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#649]
As a user, I want to be able to click on a photo within the new tabs page and be taken to the page that is associated with the tag. 

### Expected behavior: 
Clicking on the image below:
![image](https://user-images.githubusercontent.com/24685932/211190593-d44666a9-d28f-4885-bb7d-01d1195cc39c.png)

Would route the user to the first tag result associated with that photo:
https://openbeta.io/areas/24a722ea-ccee-5363-9515-3668d15132fe

### Current behavior:
Clicking on the image below does not route the user anywhere
Clicking on a tag icon takes the user to the tagged page.

**Comment by vnugent** [comment]
Fixed in #650
