### ISSUE TITLE
Update setup instructions for Windows environment

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#65]
Set up instructions are written for Mac and Linux users.  If you are a Windows user or have access to Windows:
- Go through the [README](https://github.com/OpenBeta/open-tacos#how-to-build) and verify that you can build and run the project.
- If there are missing steps, or something else you need to do differently, please document the steps.

**Comment by MichaelDimmitt** [comment]
Potentially, split this issue into 
Front End instructions (easy)
Back End instructions (more difficult due to docker concerns)

though backend should just work since backend uses node.

**Comment by MichaelDimmitt** [comment]
Backend Node.js, + Mongodb

Should instructions include windows package manager chocolatey? https://chocolatey.org/
As that is typically easiest install path for windows users.

Usually this amounts to a single link on the readme that references another markdown file of package managers

windows: choco
mac: homebrew
linux + wsl2: apt-get , other package managers

tools like `nvm`, node version manager, or asdf - a version manager for any language.

**Comment by vnugent** [comment]
> Potentially, split this issue into Front End instructions (easy) Back End instructions (more difficult due to docker concerns)
> 
> though backend should just work since backend uses node.

A backend setup is not required if you only work with the frontend.  This ticket is for instructions to set up Node, NPM/Yarn to get the frontend development env going in Windows.  I don't have access to a Windows env to know what is needed to get those 3 pieces installed.

**Comment by DarrenZLew** [comment]
> Set up instructions are written for Mac and Linux users. If you are a Windows user or have access to Windows:
> 
> * Go through the [README](https://github.com/OpenBeta/open-tacos#how-to-build) and verify that you can build and run the project.
> * If there are missing steps, or something else you need to do differently, please document the steps.

Hi, I was able to easily follow the instructions provided in the README to build and run the project for the frontend as a Windows user. This is after having already installed the listed tools in the README, which shouldn't be necessary to include given each operating system has a different way of installing said tools.

**Comment by vnugent** [comment]
Thanks for verifying.  I'm going to close this issue.
