### ISSUE TITLE
New Tags: Display tags in photo card

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#650]
As a user, I want to use the pill style tags for  `areas`/`climbs`/`+ new tags` button. 

the [TagList](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/media/TagList.tsx) component can be used to populate the card. 

remove the tag icon 
![image](https://user-images.githubusercontent.com/24685932/213326487-b14b4f12-aa44-450f-8d3e-5ecf3ff71860.png)

### Current Behavior
![image](https://user-images.githubusercontent.com/24685932/211507028-afb24a4d-34e3-45ad-8e95-8aa2e2837099.png)
### Expected Behavior
![211507428-2e78366b-93f8-44c8-8466-454b6b1666ee (1)](https://user-images.githubusercontent.com/24685932/211711873-50c2b50b-a6b4-4718-bdee-4d61d9aa8d53.png)

**Comment by andrewkykoo** [comment]
Hi @clintonlunn, I would like to work on this issue. Thanks.

**Comment by vnugent** [comment]
I'm taking on this one since it's a high traffic page and a major source of confusion.
