### ISSUE TITLE
Submit PR to open deepsourcelabs/good-first-issue to be added to their website

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#656]
When I [google search](https://www.google.com/search?q=good+first+issue&oq=good+first+issue) "good first issue", [https://goodfirstissue.dev/](https://goodfirstissue.dev/) is the first result (for me). 

They have a process outlined in their [README.md](https://github.com/deepsourcelabs/good-first-issue#adding-a-new-project) to get added to their site and promoted and I think it might help us attract more contributors.

**Comment by vcbenj** [comment]
Hey I can take on this ticket

**Comment by vcbenj** [comment]
@vnugent I sent a pr a few days ago and now we are just waiting to hear back. It looks like they haven't merged anything since October so it could be a bit.

**Comment by vcbenj** [comment]
Here's the link to my PR https://github.com/deepsourcelabs/good-first-issue/pull/552

**Comment by vnugent** [comment]
@all-contributors add @vcbenj for code

**Comment by vnugent** [comment]
Thanks @vcbenj.  What do you think if we leave this issue open until they merge the PR?

**Comment by zichongkao** [comment]
Finally done! https://github.com/DeepSourceCorp/good-first-issue/pull/552/files
