### ISSUE TITLE
Bring back page edit history

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#667]
### Use case
When viewing a climb/area page I want to see the edit history

This feature was already implemented and available in the old area page.  We just need to port it over.

Old area page:  https://openbeta.io/areas/18c5dd5c-8186-50b6-8a60-ae2948c548d1 (click on Edit -> Histor)
New ara page: https://openbeta.io/crag/18c5dd5c-8186-50b6-8a60-ae2948c548d1

**Comment by actuallyyun** [comment]
Hey I don't think the first link is working :

![Screenshot 2023-03-23 at 14 32 33](https://user-images.githubusercontent.com/87448230/227219868-bc8c9c0b-1722-4ddd-9392-766bd6fa94fa.png)

**Comment by vnugent** [comment]
Thanks for catching this.  The test area only exists in production.  In development your local app connects to the staging api server which doesn't have the same area id.  Maybe we can make the area link configurable, 1 for development and 1 for production.

**Comment by saferthanhouses** [comment]
Happy to look into this. Are there any designs available?

**Comment by saferthanhouses** [comment]
Or possibly a simple

<img width="921" alt="Screen Shot 2023-03-24 at 12 33 11 PM" src="https://user-images.githubusercontent.com/3201556/227586088-73deaffd-fd47-4377-83bf-7f4448d76b4e.png">

And showing the history popup from the old page on click

**Comment by vnugent** [comment]
@saferthanhouses thank you for taking on this.

### Pointers:
- Old area edit modal trigger: https://github.com/OpenBeta/open-tacos/blob/c22c0a25943d8eaa67534dfb7178ef14de0185a3/src/components/edit/AreaEditTrigger.tsx#L86-L90
- Edit mode toggle: https://github.com/OpenBeta/open-tacos/blob/develop/src/components/crag/cragSummary.tsx#L301-L303
- You can just add a small button next to the edit toggle for now.  The toggle is the primary call-to-action so please make the new button less prominent
- we can ask for some UX help and refine this page later in a separate PR

email me viet at openbeta dot io for additional API keys to work with auth0

**Comment by saferthanhouses** [comment]
@vnugent I'm working on updating this PR so the ChangeHistory data is pulled dynamically - not from getStaticProps as it is currently.

**Comment by vnugent** [comment]
@saferthanhouses  thanks for picking up this task.  
Do you think there's a huge benefit in pulling the data dynamically since the majority of our users simple read the pages?

**Comment by saferthanhouses** [comment]
@vnugent possibly not! But it was a good opportunity to dig into the different SSR strategies the app is using 😆 
PR reopened.
