### ISSUE TITLE
Handle backend token expired gracefully

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#673]
## Expected Behavior
Auth0 login session is valid for 1 month.  The frontend should either force the user to re-login or refresh the session silently.

## Current Behavior
Even though the UI says I'm logged in, making an edit and save will cause the backend to throw a http 500 error (should 401).  

## Possible Solution
It doesn't seem easy to refresh an Auth0 login session silently.  Perhaps parse API calls for  "expired token" message and force a relogin.

---

<img width="1431" alt="Screen Shot 2023-01-28 at 2 46 01 PM" src="https://user-images.githubusercontent.com/3805254/215270199-af40446c-dc64-42bd-9f3a-687b1aee4fa5.png">

**Comment by julianlam** [comment]
Thanks @musoke, both #1179 and #673 (this issue) involve an API call failing. I linked to #1159 which details different behaviour, but could be related as it is a *page load* instead of an API call.

**Comment by julianlam** [comment]
> It doesn't seem easy to refresh an Auth0 login session silently. 

@vnugent Auth0 should send `refresh_token` alongside the `access_token`. If you save that to the db as well, then you can use that token to silently refresh the user session on call failure (or pre-emptively on token expiration)

**Comment by musoke** [comment]
Loading /edit does seem like something that could require a valid session.  I think fixing this issue would clear up a bunch of bug reports.

**Comment by vnugent** [comment]
> Loading /edit does seem like something that could require a valid session. I think fixing this issue would clear up a bunch of bug reports.

Yup.  we should upgrade the auth library or consider switching to the official Auth0 Next library (it wasn't available at the time we introduced authz).  I used the Auth0 lib for work and can confirm that it handles refresh token.

**Comment by musoke** [comment]
@nthh, this is the issue we discussed
