### ISSUE TITLE
Overflow issue user gallery page

### ISSUE THREAD

**Issue by tedgeving** [OpenBeta/open-tacos#678]
This issue tracker is **ONLY** used for reporting bugs!

Horizontal scroll bar is visible when the screen size is below 1022px, Appears to be caused by long image captions.
http://localhost:3000/u/viet-test-profile

## Expected Behavior
Horizontal scrollbar should be hidden on small screen sizes.

## Possible Solution
add `overflow: hidden` to image container

## Steps to Reproduce
1. Navigate to user gallery page: http://localhost:3000/u/viet-test-profile
2. Make screen smaller than 1022px
3. Horizontal scroll bar should be visible. See Screen Shot.

![Screen Shot 2023-02-01 at 1 38 35 PM](https://user-images.githubusercontent.com/24211/216159109-466b8768-88df-43dc-979f-726111cf7eb5.png)

Image with `overflow: hidden` added to  the image container `<div class="relative"></dvi>`

![Screen Shot 2023-02-01 at 1 38 43 PM](https://user-images.githubusercontent.com/24211/216158988-eec91af5-0d19-40a0-87f3-c877456568e2.png)

**Comment by vnugent** [comment]
Not sure this is related (see screenshot).  Maybe use Tailwind text overflow to add ellipsis to shorten long tag. https://tailwindcss.com/docs/text-overflow

<img width="890" alt="Screen Shot 2023-02-02 at 12 34 51 PM" src="https://user-images.githubusercontent.com/3805254/216314396-45230751-aeda-4314-bda8-a65190ea06ed.png">

**Comment by tedgeving** [comment]
@vnugent  
Your suggestion/solution is correct, I guess the text description does not wrap on those cards. You can assign this to me should be a quick fix.
