### ISSUE TITLE
Create a Docker file to simplify build setup

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#68]
Use case:
As a contributor I don't want to deal with installing node, gatsby-cli on my computer.   The Dockerfile should contain everything needed to execute the build.

1.  Create a Dockerfile that includes, node.js, npm, yarn, gatsby-cli
2. Document this new way of doing build in README.md

Example:
https://github.com/EnterpriseDB/docs/blob/develop/docker/docker-compose.quickstart.yaml

**Comment by basalt79** [comment]
@vnugent  i will give it a try

**Comment by vnugent** [comment]
> @vnugent i will give it a try

Great!  We're hanging on on Discord (link in Contributing.md) if you have any questions.
