### ISSUE TITLE
Image should be in larger size on click in gallery section

### ISSUE THREAD

**Issue by theonlyjunaid** [OpenBeta/open-tacos#685]
The issue is on the Gallery section of post. If we click on any image that image should view in larger size for the better interection

## Expected Behavior

If we click on any image that image should view in larger size for the better interection
## Current Behavior

If we click on any image nothing is happening except some effect on hover

## Possible Solution

the solution could be a component in which that clicked imaged view in larger size

**Comment by theonlyjunaid** [comment]
assign me i will solve it

**Comment by vnugent** [comment]
@theonlyjunaid thank you for reporting the behavior and offering help to improve the app!

Can you please share a rough outline for the PR?  A simple mockup, screens you want to add, etc.  Thank you.

**Comment by theonlyjunaid** [comment]
current problem

https://user-images.githubusercontent.com/95287515/217546350-edf80d42-abe1-4cc0-9b03-c364f50de66b.mp4

my solution

https://user-images.githubusercontent.com/95287515/217546985-18b3bb1a-8ad2-4b54-9052-769290094aae.mp4

**Comment by vnugent** [comment]
Great. Thank you.  Go for it!
