### ISSUE TITLE
Prompt users to change their user name

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#686]
## Expected Behavior
When a user signs up, the app generates a random user name.   Most users don't know they can and should change this.

## Current Behavior
 Most users don't know they can and should change this.

## Possible Solution
- Force users to change their user name
- Add a text prompt

## Steps to Reproduce
1.  Log in and navigate to Profile
2. Click edit

<img width="666" alt="Screen Shot 2023-02-08 at 9 33 36 AM" src="https://user-images.githubusercontent.com/3805254/217478001-5a5b5b8f-2191-4220-9de3-5656a99015c3.png">

---
### Mockup
1.  Add a tip explaining user name may be changed
2. Rename Name -> Display Name

<img width="666" alt="Screen Shot 2023-02-08 at 9 33 36 AM" src="https://user-images.githubusercontent.com/3805254/217492444-265a8e8a-e8c1-49cb-8551-000ff514abd2.png">

### Tips:
- Email viet at openbeta dot io to get Auth0 credential (so that you can log in)
- Edit profile component https://github.com/OpenBeta/open-tacos/blob/develop/src/components/users/account/ProfileEditForm.tsx#L134

**Comment by kunal00000** [comment]
Hi @vnugent ,
I would like to work on this issue. Can you assign this to me.

**Comment by kunal00000** [comment]
Emailed for auth0 credentials at viet@openbeta.io

**Comment by vnugent** [comment]
@kunal00000 please check your email

**Comment by kunal00000** [comment]
See if this works @vnugent .

https://user-images.githubusercontent.com/92316166/217826961-3d9f645f-496b-4452-96f1-7076d4a1fc8c.mov

**Comment by vnugent** [comment]
@kunal00000 looking great.  Can you rename "Name" to "Display name" as shown in the mockup?
Thank you

**Comment by kunal00000** [comment]
> @kunal00000 looking great.  Can you rename "Name" to "Display name" as shown in the mockup?
> Thank you

Yes, I have done that but recorded this video before doing that 🙂
