### ISSUE TITLE
Clicking on user name should take me to their profile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#688]
## Expected Behavior
When I click on a user name or the user icon I expect to go to their user profile

## Current Behavior
Instead the link takes me to the tagged page

## Possible Solution
Look at RecentImageCard component https://github.com/OpenBeta/open-tacos/blob/develop/src/components/home/RecentMediaCard.tsx#L30

## Steps to Reproduce
Go to https://openbeta.io

---
<img width="885" alt="Screen Shot 2023-02-08 at 2 32 20 PM" src="https://user-images.githubusercontent.com/3805254/217548265-bfeb18db-c784-4bd4-bcf7-535f4e851c20.png">

**Comment by ParthParolekar** [comment]
I would like to work on this issue. Can you assign this to me?
