### ISSUE TITLE
architecture diagram flow

### ISSUE THREAD

**Issue by SkyBulk** [OpenBeta/open-tacos#705]
what kind of software did you use to create the following architecture design? 

https://github.com/OpenBeta/open-tacos/blob/develop/OpenBeta-arch1.png

**Comment by vnugent** [comment]
I use Figma & Fig Jam

**Comment by vnugent** [comment]
@SkyBulk if you have more questions, ask us in the Discord server https://discord.com/invite/ptpnWWNkJx
