### ISSUE TITLE
Tick lists in opentacos don't reflect additions/deletions visible through API

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#727]
I attempted to delete an ascent but was unable to do so.

## Expected Behavior

The tick should disappear from my tick list.

## Current Behavior

The tick remains in my tick list but I don't see the 
![image](https://user-images.githubusercontent.com/16665084/224569090-e2a577cd-4172-4839-b187-264897265901.png)
 button on the climb's page.

## Steps to Reproduce

1. Tick a climb.
2. Import ascents from mountain project.
3. See that tick is duplicate in log book.
4. Attempt to delete an ascent that is now a duplicate.
5. Check tick list again.  See that both ascents are still there.

## Context (Environment)

I added an ascent before trying to import from mountain project.  I am attempting to delete a duplicate tick.

**Comment by musoke** [comment]
This is likely a cache issue.  It remains on the list at https://openbeta.io/u2/theoretical_gray_condor but querying the API [through hasura](https://cloud.hasura.io/public/graphiql?endpoint=https%3A%2F%2Fapi.openbeta.io%2F) returns a shorter list of ticks.

This is the query I used:
```
query MyQuery {
  userTicks(userId: "8e1a19d4-7339-4100-8b94-85bcc7d98adc") {
    _id
    userId
    name
    notes
    climbId
    style
    attemptType
    dateClimbed
    grade
    source
  }
}
```

**Comment by vnugent** [comment]
If it's indeed a caching issue we can add a revalidate cache value in seconds (Read more about [revalidation](https://beta.nextjs.org/docs/data-fetching/revalidating)).

- locate /u2/[...slug].tsx page

 https://github.com/OpenBeta/open-tacos/blob/cc68c16ea8c6ecd04880e6baf014020940acb355/src/pages/u2/%5B...slug%5D.tsx#L73
- Add `revalidate: 10` to the return object
```javascript
return {
  props: { uid, ticks },
  revalidate: 10
}

```

**Comment by musoke** [comment]
👍
