### ISSUE TITLE
Overly strict coordinate parsing

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#730]
## Context (Environment)

I have been adding coordinates to some areas.  I have noticed that coordinates with a space in them are not allowed.  This is strange, given that that this is the format displayed by opentacos, e.g.
![image](https://user-images.githubusercontent.com/16665084/225505364-9aa9c4fb-a25e-4147-a72b-2f44fc1e60d7.png)

## Steps to Reproduce

1. Navigate to an area, enter edit mode
2. Add coordinates with a space between the latitude and longitude, for example "48.26000, 2.67000".  

## Expected Behavior

The editor accepts the coordinates and lets the user save them.

## Current Behavior

The editor complains that coordinates are invalid.

![image](https://user-images.githubusercontent.com/16665084/225504807-888ca2bd-0668-425b-928b-0afcd09fad2b.png)

Removing the space is sufficient to fix the error.

## Possible Solution

Coordinates with one or more spaces between the comma and longitude should be allowed.  The space introduces no ambiguity.

**Comment by vnugent** [comment]
Thank you. I'm leaving a tip below in case you or anyone else can help address this issue.

### How to fix
1.  Locate the following regex https://github.com/OpenBeta/open-tacos/blob/develop/src/components/edit/EditAreaForm.tsx#L12
2. Add `\s*` right after the comma
3. Copy the entire regex to https://regex101.com/ and verify that it supports 1 or more spaces
