### ISSUE TITLE
Sign up page logo image not displayed

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#745]
## Steps to Reproduce

1.On a crag page, click on `edit mode`
2.Sign up page poped up

## Screenshots
![Screenshot 2023-03-22 at 15 11 00](https://user-images.githubusercontent.com/87448230/226931510-d5a722db-4789-4b97-a2d0-1ca4f8224098.png)

## Expected Behavior

The logo should be displayed

## Current Behavior
The logo not showing 

## Browser & version
Chrome Version 111.0.5563.64 (Official Build) (x86_64)
## Operating system
<--- Example:  MacOS 13.2.1 -->
MacOS 10.15

**Comment by vnugent** [comment]
For future reference:
1. Log in Auth0.com
2. Branding --> Universal login --> Customization Options
3. Style | Widget --> Logo url (on the right hand side)

url: https://openbeta.io/openbeta-logo-192x192.png
