### ISSUE TITLE
Add social media card for climb and area

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#75]
https://css-tricks.com/essential-meta-tags-social-media/

**Comment by gibboj** [comment]
@vnugent Looking at this ticket, it seems like the tags already exist on those pages via [SEO](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/seo.js). Did you want me to add more information to the card? Or am I totally misunderstanding the ticket?

Example of whats there for a climb: https://tacos.openbeta.io/usa/oregon/southwest-oregon/callahans-the/mind-planet/booder-skies
<img width="579" alt="Screen Shot 2021-12-22 at 17 10 41" src="https://user-images.githubusercontent.com/2992272/147122083-a08d75b3-354a-4f6f-be98-f95bde1f3a06.png">

**Comment by vnugent** [comment]
How about adding additional information.  Some ideas:
- name of the wall
- FA field
- a small `ogimage `.  It can be static, same image for all pages.
