### ISSUE TITLE
How to encourage people to set their user id and display name?

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#750]
**What would you like to be able to do? Please describe.**
When looking at the user profile edit page, most people don't know:

1.  You can change the auto-generated user id to your own unique id (no space allowed, similar to IG or Twitter handle)
2. Display name can be a human-friendly name with space Ex:  "Jane Doe".  A lot of people would put "jane.doe".

**How important is this to you** (Please pick one)
- Nice-to-have

### To do:
- [ ] Suggest small UI changes to encourage people to set a user name and a display name

<img width="650" alt="Screenshot 2023-03-23 at 11 57 35 AM" src="https://user-images.githubusercontent.com/3805254/227184306-f8bb6b3f-a833-4952-be2e-01209feff26c.png">

**Comment by clintonlunn** [comment]
@vnugent is there a way to figure out if the username/display name is the default randomly generated name? It might be nice to only tell the user that they can change their name if they haven't already changed it before.

**Comment by vnugent** [comment]
The auto-generated name has the following format: `<random adjective>_ <random color>_<random animal>`.    

What we can also do is somehow detect if it's the first login, the code would clear the auto-generated name, forcing the user to change it if they want to update the profile.

**Comment by clintonlunn** [comment]
@vnugent 

Ok there is a [loginsCount](https://github.com/OpenBeta/open-tacos/blob/e6bdcc17f97a2e155c5dd34cc5e8185da2efd743/src/js/types/User.ts#L4) property that comes in with the [userProfile](https://github.com/OpenBeta/open-tacos/blob/f043f174e76a5d632a2ff4778955c59665fd544c/src/components/users/PublicProfile.tsx#L24) property. 

How about we open a tooltip on the user's first login?
![image](https://user-images.githubusercontent.com/24685932/233225116-00c12411-c299-4f5b-a543-b8790fcb8ea0.png)

I can take issue.

**Comment by clintonlunn** [comment]
@vnugent how would you feel about routing the user directly to the edit profile page after creating a profile? Then, if it's their first login, we can activate some sort of a stepper component

![image](https://user-images.githubusercontent.com/24685932/234719356-4e4a2016-596f-459f-987a-7f81381e5163.png)


and if it's not their first login, they'll only see the normal form
![image](https://user-images.githubusercontent.com/24685932/234719697-ade1cf37-aaae-4c6b-ab3a-83bbae716033.png)

**Comment by vnugent** [comment]
New users are now required to pick a username.
