### ISSUE TITLE
Typo on About page

### ISSUE THREAD

**Issue by Colb131** [OpenBeta/open-tacos#755]
## Steps to Reproduce

1. Open About Page at https://openbeta.io/about
2. Scroll down to `Why we need your donations`
3. Observe typo.

## Screenshots

![image](https://user-images.githubusercontent.com/64448561/227649727-07287b4d-abcc-41a4-8835-93dd96bbc0ac.png)

## Expected Behavior

Should say, "nor `is it` supported by ads. Fortunately`,` there is a small"
## Current Behavior

Says "nor it is supported by ads. Fortunately there is a small"
## Browser & version
<---  Example: Firefox 102.7.0esr  -->
Google Chrome 111.0.5563.111
## Operating system
<--- Example:  MacOS 13.2.1 -->
Windows 11 Pro 22H2

**Comment by danekshea** [comment]
Thanks @Colb131 for your thorough documentation of this. Fix has now been merged. @vnugent can we close?

**Comment by vnugent** [comment]
@all-contributors add @Colb131 for bug
