### ISSUE TITLE
Display FA and GPS information when available

### ISSUE THREAD

**Issue by ygingras** [OpenBeta/open-tacos#76]
When GPS and FA information are provided, they should be rendered. 

For example, many of the routes at Pete's Pile have this information but it is not rendered: 
https://tacos.openbeta.io/usa/oregon/mt-hood/petes-pile/6-quiky-combat-wall

**Comment by nadr0** [comment]
Based on https://github.com/OpenBeta/open-tacos/pull/81; I don't think a climb should inherit the parent areas lat lng. 

I think a climb should have the climb's lat lng or no lat lng. It shouldn't have the parent's as a filler. We should render the climb's lat lng if it is present. 

@vnugent

**Comment by vnugent** [comment]
FA
<img width="744" alt="Screen Shot 2021-10-17 at 7 45 33 AM" src="https://user-images.githubusercontent.com/3805254/137611843-6b1cbf80-787e-49e4-9c31-e1c64cafbec5.png">

---

GPS
<img width="722" alt="Screen Shot 2021-10-17 at 7 46 31 AM" src="https://user-images.githubusercontent.com/3805254/137611869-6fae5076-ef94-4772-8a8e-5d52e0e14f03.png">

**Comment by musoke** [comment]
I agree that climbs and areas should not inherit locations from their parents.

In fact, it should be the opposite: unless the location is set explicitly, it should be displayed on the map as the smallest rectangle that encompasses all child areas and climbs that do have a location set.  If a single coordinate is needed, the centre of that rectangle could be used.

**Comment by vnugent** [comment]
Current state
1.  Climbs still inherit GPS of the crag.  
2.  Parent areas: when we seeded the database last year, parent areas GPS are calculated using the [centroid function](https://turfjs.org/docs/#centroid) where vertices are child areas' GPS.  Though you can go to the area page and edit this value.

> In fact, it should be the opposite: unless the location is set explicitly, it should be displayed on the map as the smallest rectangle that encompasses all child areas and climbs that do have a location set. If a single coordinate is needed, the centre of that rectangle could be used.

We can certainly create a bounding box and draw a rectangle if you think there's a need/use case for it.

I'm going to close this issue now as the FA field issue has been fixed.  I think if you feel strongly about having GPS for individual climbs or some kind of GPS + relative location (left of the tree) as suggested by @on3iropolos  please create a separate issue.
