### ISSUE TITLE
(0) Create a LCO List component based on new Figma design

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#763]
Impact: 2
Complex: 2

Task: 0

**Comment by actuallyyun** [comment]
Hi @vnugent I could probably work on this task. Where can I find the Figma design?

**Comment by ajmody** [comment]
@actuallyyun  and myself went over the figma designs today. We will connect again if she anymore design specs, otherwise we'll correspond within figma, discord, email, etc.
