### ISSUE TITLE
(0) Create a new LCO Profile card component based on new Figma design

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#764]
Impact: 2
Complex: 2

**Comment by saferthanhouses** [comment]
@vnugent happy to take this on, would need access to the designs.

**Comment by vnugent** [comment]
@saferthanhouses 
I believe Yun has already been working on this one.  If you're interested in working on similar tasks, UI building components please ping me in the Discord. We can identify some new tasks. Thanks.

**Comment by zichongkao** [comment]
https://github.com/OpenBeta/open-tacos/pull/813
