### ISSUE TITLE
Remove 'the first' from about page

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#768]
Remove "the first" from the about page https://openbeta.io/about

> Inspired by Wikipedia and OpenStreetMap, we're building the first open source & open license rock climbing catalog.

Source https://github.com/OpenBeta/open-tacos/blob/develop/src/pages/about.tsx#L17

**Comment by Ksj14-kumar** [comment]
Hi @vnugent, is anyone working on this issue? if not then please assigned it to me I want to contribute on it.

**Comment by vnugent** [comment]
@Ksj14-kumar Thanks for asking.  Sorry it was completed by @sjdex

**Comment by Ksj14-kumar** [comment]
@vnugent, okay no problem.
