### ISSUE TITLE
Update PACC profile

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#779]
From PACC
---

For crags we can put our name to i would say:

    Broughton
    Beacon
    Windy Slab
    Horsethief Butte
    Wankers Columns
    Beacon Rock
    Viento
    Rat Cave
    Kiwanis Camp
    Salmon Slab
    OH8
    Frenchs Dome
    Klinger Spring
    Petes Pile
    Area 51
    Bulo Point
    Empire Boulders
    TLC
    Hunchback

Additionally there are these locations we wth, but access isn't as formal

    Ozone
    Farside/Dropzone
    Rocky Butte

We also work at 2 but aren't the primary group

    Madrone Wall
    Carver Cliff

**Comment by clintonlunn** [comment]
@vnugent Is this updating the [data.tsx](https://github.com/OpenBeta/open-tacos/blob/develop/src/components/lco/data.tsx#L26-L39) file? I can probably take this.

**Comment by vnugent** [comment]
Yes please!
