### ISSUE TITLE
Add area grade distribution back

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#78]
When reorganizing/refactoring gatsby-node.js (PR https://github.com/OpenBeta/open-tacos/pull/77) I decided to remove area grade/climb type distribution introduced by PR https://github.com/OpenBeta/open-tacos/pull/51.

~~With the new Area and Climb nodes, we can write simple code/graphql query to calculate area statistics.  I suggest doing the calculation in each sub-area instead of doing in `leaf-area-page-md.js`.~~

Use the new [graphql](https://github.com/OpenBeta/openbeta-graphql) api

**Comment by gibboj** [comment]
@vnugent Where do we want to add this to? The subarea cards?

**Comment by vnugent** [comment]
This is issue out of date.  You can see what it looked like before it was removed: https://github.com/OpenBeta/open-tacos/pull/51

I think we may want to reconsider how we show stats on area page using technical charts & graphs.  Perhaps, let's consider 2 personas and 2 separate tools for each:

1.  Area/crag view: for climbers to quickly learn about an area.  "Can I climb here?"
  - Use simpler infographics.  Example:  

![!is it for me](https://image.shutterstock.com/image-illustration/skill-levels-260nw-464948405.jpg)


2. Explorer tool: For advanced users
- advanced filters by grades, disciplines
- Large maps with multiple layers (street, topos, weather, 3D terrains etc)
- Aggregate data from other sources such as OpenStreetMap with climbing, recreation tags
- Data export wizard

**Comment by gibboj** [comment]
Ok let's close it if it's not relevant any more. I move the comment & image to Figma to put it in with the other ideas so we don't lose track of it
