### ISSUE TITLE
update ts-standard to 12.0.0

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#787]
## Steps to Reproduce

1. clone https://github.com/OpenBeta/open-tacos/
2. yarn install
3. yarn lint

## Expected Behavior

package versions in package.json are mutually compatible. 

## Current Behavior

Get warning

```
=============

WARNING: You are currently running a version of TypeScript which is not officially supported by @typescript-eslint/typescript-estree.

You may find that it works just fine, or you may not.

SUPPORTED TYPESCRIPT VERSIONS: >=3.3.1 <4.5.0

YOUR TYPESCRIPT VERSION: 4.9.5

Please only submit bug reports when using the officially supported version.

=============
Done in 9.33s.
```

## Steps to fix

See also fix of similar issue in https://github.com/OpenBeta/openbeta-graphql/pull/265

- change https://github.com/OpenBeta/open-tacos/blob/5be4774db2b0261dfac8603e55749dc2d67ee42e/package.json#L111 to version 12.0.0
- `yarn install`
- add and run `yarn fix` script as in https://github.com/musoke/openbeta-graphql/blob/0b193c16c880127a15171ae39459a0f48350da11/package.json#L60
- fix lints that can't be fixed automatically 
- remove warning from readme: https://github.com/OpenBeta/open-tacos/blob/be2064a64974b9dbebea8f49dc98d275aa495289/README.md?plain=1#L125-L127

**Comment by giri-madhan** [comment]
Hi @musoke, could you please assign this issue to me? I can work on making these changes. Thank you!

**Comment by actuallyyun** [comment]
Amazing! I have been seeing this error as well, thanks for fixing it in the other repo! @musoke  I could open a PR to fix it in this repo if this sounds good to you guys. @vnugent

**Comment by actuallyyun** [comment]
Hey @musoke after running `yarn fix`, I still got many linting errors, and most of them are about this rule:https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/no-misused-promises.md

![Screenshot 2023-04-27 at 16 51 59](https://user-images.githubusercontent.com/87448230/234901057-30040b8a-8a0d-4824-bfdb-105abcf7e1e9.png)

Should I fix this error or ignore this rule? 
There are also two errors about triple slashes :
```
  /Users/Ayun/webDev/OpenSource/open-tacos/next-env.d.ts:1:1: Do not use a triple slash reference for next, use `import` style instead. (@typescript-eslint/triple-slash-reference)
  /Users/Ayun/webDev/OpenSource/open-tacos/next-env.d.ts:2:1: Do not use a triple slash reference for next/image-types/global, use `import` style instead. (@typescript-eslint/triple-slash-reference)
``` 

But in the `next-end.d.ts` file, it writes 
```
// NOTE: This file should not be edited
// see https://nextjs.org/docs/basic-features/typescript for more information.
```

**Comment by musoke** [comment]
This is probably a question for @vnugent, he wrote most of the code it still complains about


Triple slash imports: https://nextjs.org/docs/basic-features/typescript says that `next-env.d.ts` shouldn't be committed.  @vnugent added it in f4c5c75d579b4bab6708c0c741d39098e6d47885 - is it ok to remove?

PS: probably best to time this carefully with the other incoming PRs, this touches enough files that it may conflict with a lot of them

**Comment by hawkishpolicy** [comment]
Is this still an active issue?

**Comment by musoke** [comment]
@actuallyyun had a partial fix.  I don't know if she is still working on it or it is up for grabs.

**Comment by vnugent** [comment]
> Triple slash imports: https://nextjs.org/docs/basic-features/typescript says that `next-env.d.ts` shouldn't be committed. @vnugent added it in [f4c5c75](https://github.com/OpenBeta/open-tacos/commit/f4c5c75d579b4bab6708c0c741d39098e6d47885) - is it ok to remove?

It was an oversight

> is it ok to remove?

 sure

**Comment by actuallyyun** [comment]
Sorry for the late reply. Hi @hawkishpolicy it is up for grabs! I started it but then I got many linting errors that require decisions beyond my ability. For instance, the `no-misused-promises` rule triggered a lot of errors all over the place. I am not sure if we should fix these errors or disable this rule. There are many other rules like this one.

**Comment by hawkishpolicy** [comment]
I don't know if I can do any better but I'll take a look if that's okay.

**Comment by vnugent** [comment]
~~Added @hawkishpolicy to core-dev team~~ commenting on the wrong issue

**Comment by hawkishpolicy** [comment]
What's the best way to check if the script worked?

I followed the instructions provided and I'm not getting any errors but i'd like to double check before I submit a PR

**Comment by musoke** [comment]
I would delete `node_modules`, `yarn install` again and try `yarn lint`.  One of us can also try it once you make a PR.

**Comment by musoke** [comment]
@hawkishpolicy, did that work for you?

**Comment by hawkishpolicy** [comment]
Partly...I'm getting quite a few ES-Lint errors that I need to track down.
Just been busy with contract work and family.

**Comment by musoke** [comment]
Ok, just wanted to make sure you're not stuck waiting for us.

**Comment by Ali7040** [comment]
please assign it to me. I want to work on it

**Comment by hawkishpolicy** [comment]
I still hit many errors after running the script and haven't had time to
dig through the documentation.

I'm more than happy to forgo this one.

**Comment by vnugent** [comment]
@Ali7040 If you're working on this issue, please do a rebase with `develop`.  I had to turn on Typescript strict mode for Issue #811 and ended up fixing / suppressing warnings in nearly 90 files.

**Comment by Ali7040** [comment]
I am already working on develop branch.

**Comment by Ali7040** [comment]
![image](https://github.com/OpenBeta/open-tacos/assets/81979505/56dd159e-058a-4b89-8828-b264dc951909)
I just used `yarn upgrade`, and now everything works fine with `"ts-standard": "11.0.0"`. Should I change it to `"ts-standard": "12.0.0"` or not?

**Comment by musoke** [comment]
@Ali7040, do you have a branch or draft PR you can share?

**Comment by Ali7040** [comment]
@musoke  I haven't created a PR yet.

**Comment by Ali7040** [comment]
I just upgraded things, so it only changes the `yarn.lock` file. If you want, I can create a PR.

**Comment by musoke** [comment]
Please do

**Comment by Ali7040** [comment]
Check it out: https://github.com/OpenBeta/open-tacos/pull/939

**Comment by vnugent** [comment]
@Ali7040 thanks for giving this issue a try.  It turns out more complicated than I thought.
