### ISSUE TITLE
[New LCO]: Skaha collective

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#792]
Note from my contact

> Please add the SCARS link [https://scarspenticton.com](https://scarspenticton.com/?fbclid=IwAR2qVr07s8z_vwpsO9DL4uNLknEUROUWIQipSts9Sx9AkLBm8JP6ASiL2Wo). But also just as important the ParkWatch link [http://www.skahabluffsparkwatch.com](http://www.skahabluffsparkwatch.com/?fbclid=IwAR1Ff9pUrxXjPQ7lPEysFldg_RtqWN4YRcMHJquD9kKrhZ-J1CqB6dQhEmM).
ParkWatch site has all the updated new routes not in Marc’s guide book

**Comment by clintonlunn** [comment]
@vnugent I added this organization along with other info I could find. Does that close this issue?

orgId: dd8402eb-9a2c-409c-9bdb-00012bb2724d

![image](https://user-images.githubusercontent.com/24685932/236970158-7226ffb2-b69e-4e45-a78e-139ae372e4d2.png)
![image](https://user-images.githubusercontent.com/24685932/236970283-d8113612-4a08-41ce-83d8-53bba86d90c0.png)
