### ISSUE TITLE
Fix CSVEditor test

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#793]
The CSVEditor test fails randomly.  The highlighted code checks to see if the OK button is disabled when there's an error in the editor.

https://github.com/OpenBeta/open-tacos/blob/86d1f123f7fabd26afbcf3849ee87aed2886d780/src/components/editor/__tests__/CsvEditor.tsx#L106

We're currently exclude the test suite.  

## To do:
- Reenable the test suite
- Reproduce the failure
- Come up with a more reliable test

## Steps to Reproduce

1.  Fork open-tacos
2.  Make sure you can build the project locally
3. Reenable the test suite: change xdescribe -> describe https://github.com/OpenBeta/open-tacos/blob/86d1f123f7fabd26afbcf3849ee87aed2886d780/src/components/editor/__tests__/CsvEditor.tsx#L11
4.  Run `yarn test csveditor` (you might have to re-run a few times to see the error)

**Comment by musoke** [comment]
I wonder if it's actually a real bug in CSVEditor?  I sporadically see odd errors when using it, but haven't been able to pin them down well enough to file a specific bug report.

**Comment by actuallyyun** [comment]
I played with it a bit and passed the test by changing the user input from `5f` to `5hf` 

` await user.type(editor, '{arrowleft>4}{backspace}hf') `
`await user.type(editor, '{arrowleft>4}{backspace}{backspace}b') `

Somehow in the test, just changing `5c`=>`5f` does not disable the button, `5hf` does. 

btw, I have not had problem with the csv editor so far.

**Comment by vnugent** [comment]
> Somehow in the test, just changing 5c\=\>5f does not disable the button, 5hf does.

Interesting.  The failure is sporadically.  Often times it passes in local dev env, but would fail in GitHub action.

@musoke could be related to #796
