### ISSUE TITLE
[New LCO] Kalymnos Rescue Team

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#801]
Name: Kalymnos Rescue Team
Web: http://www.kalymnosrescueteam.org/
FB: https://www.facebook.com/kalymnos.rescue.team/
IG: N/A
Donation: https://www.paypal.com/donate/?cmd=_donations&business=kalymnosrescue%40gmail%2ecom

**Comment by clintonlunn** [comment]
@vnugent I added this LCO. Good to close?
![Image](https://user-images.githubusercontent.com/24685932/236999492-ca09d259-2432-4148-a968-dd87c5d3f97c.png)





![Image](https://user-images.githubusercontent.com/24685932/236999560-d6fe33eb-96fa-4276-b119-8153ea0343fc.png)
