### ISSUE TITLE
Add Basecamp functionality to create, update and delete organizations

### ISSUE THREAD

**Issue by zichongkao** [OpenBeta/open-tacos#803]
Impact 3 (We would use this to support a general launch)
Complexity 2 (Not public-facing UI, fairly transparent logic calling backend APIs)

---

Basecamp is our internal admin UI. We want to add functionality so admins (ie us) can create, update and delete organizations. This would enable us to change the data in our datastore without needing to manually reach in and modify data, which is dangerous and error prone. 

This task would be primarily a UI task. It would call API endpoints that we've already built (*delete endpoint isn't built yet, it is tracked under https://github.com/orgs/OpenBeta/projects/6/views/1?pane=issue&itemId=25523811 though). For a start, we probably don't need to implement bulk creation or updating. Just assume we have few LCOs we need to manage, so it's not to much to ask to do each one individually.

**Comment by zichongkao** [comment]
Addressed in https://github.com/OpenBeta/open-tacos/pull/788/files, but not handling deletion just yet.

**Comment by actuallyyun** [comment]
Hey @zichongkao Are you working on the UI task yourself?

**Comment by zichongkao** [comment]
Yeah - I figured since basecamp is an internal facing dashboard, that
something simple would do, so I simply extended the design patterns of the
existing UI.

But I'm no frontend expert, you can view the screenshots or the actual
layout at stg.openbeta.io/basecamp/organizations (you'll need to assign
your account a user_admin role in Auth0) and let me know if you have
suggestions for improvement! I'm trying to hone my UI design skills too 🙂
