### ISSUE TITLE
Remove Formik and replace with react-hook-form

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#811]
We now use https://react-hook-form.com/ to manage our forms. We previously used Formik

Remove any uses of Formik (and the yup validation that would go along with it) and replace with React Hook Form

**How important is this to you** (Please pick one)
- Important

**Comment by vnugent** [comment]
Form controls: https://github.com/OpenBeta/open-tacos/tree/develop/src/components/ui/form

**Comment by vnugent** [comment]
New changes in PR https://github.com/OpenBeta/open-tacos/pull/838 link that impact this issue

- New API to update profile data
- Username change is in its own screen

I've disabled the link to the current profile edit form.

---
<img width="533" alt="Screenshot 2023-06-07 at 9 39 16 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/f051d9c5-bce7-4603-b32b-c900060e54e8">

**Comment by vnugent** [comment]
@clintonlunn did you already spend a lot of time on this?

I was working on a screen for setting / updating username https://github.com/OpenBeta/open-tacos/pull/838 and can extend it to replace the old user name profile.

**Comment by clintonlunn** [comment]
@vnugent I had started on this but a bit of life has gotten in the way lately and my ability to commit time is near nothing at the moment. Feel free to remove me from this issue, thanks!

**Comment by vnugent** [comment]
No worries.  I can definitely work on this.  Just want to make sure we're not duplicating efforts.

**Comment by vnugent** [comment]
You can now update your profile at https://openbeta.io/account/editProfile
