### ISSUE TITLE
Replace Snackbar component with react-toastify notification in ProfileEditForm.tsx

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#814]
Currently, our app uses the [Snackbar](https://github.com/OpenBeta/open-tacos/blob/eb13d0fe22a211f3201ccd9eee606504700f721a/src/components/ui/Snackbar.tsx#L3) component to display a message to the user when their profile is updated. This component is only used in the [ProfileEditForm.tsx](https://github.com/OpenBeta/open-tacos/blob/eb13d0fe22a211f3201ccd9eee606504700f721a/src/components/users/account/ProfileEditForm.tsx#L7) file.

I propose replacing the Snackbar component with the toast.info or toast.success function provided by the `react-toastify` library.

The updated ui would look something like this:
![image](https://user-images.githubusercontent.com/24685932/236731430-29bcf4b8-7090-4591-8c05-a491d11c3135.png)

to something like
![image](https://user-images.githubusercontent.com/24685932/236732290-fd7d0bf7-ac1c-4c38-bbb1-43268a84992f.png)

**How important is this to you** (Please pick one)
- Nice-to-have

**Comment by hawkishpolicy** [comment]
I think I have this resolved.
