### ISSUE TITLE
[New LCO] Add Crag care Ottawa, Ontario, Canada

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#815]
Info: https://www.instagram.com/cragcare_ottawa/
facebook: https://www.facebook.com/OttawaCragCare/

**Comment by clintonlunn** [comment]
![image](https://github.com/OpenBeta/open-tacos/assets/24685932/f49d8838-4dbe-4255-a76e-1e4e2759bbe5)
added
