### ISSUE TITLE
(5) Transfer organization data from spreadsheet into the database

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#816]
This task will probably take ~ 2h:
- 1h to get permissions, and familiarize with basecamp.
- 1h to enter the 40+ orgs. Perhaps more to verify that organizations are tied to the correct area ids.

Data is currently stored here: https://docs.google.com/spreadsheets/d/1Mtb-q4gsg_fc-8B6ecDTlU8XBRjswvVs9HdbU2OTNUk/edit#gid=0

Task is to go to https://www.openbeta.io/basecamp/organizations and add them into our database. Note that your account would need `user_admin` privileges to access basecamp.

-----
Update with the specific data available, knowing that new data may be available later.

**Comment by clintonlunn** [comment]
@vnugent I added about 30 LCO's to the organizations list within the basecamp admin dashbaord. I can continue to go with that or we can leave as is and fill in later. While it does have orgs that we have not had agreement from, it does cover al of the orgs we do have agreement from (assuming the google sheet referenced above was up to date)



![Image](https://user-images.githubusercontent.com/24685932/236999975-99a360dc-3917-4d1d-9fdf-3cd907d1ab7a.png)



The number of LCO's displayed is capped at 20, so this doesn't actually display all of the LCO's that I added. But I know we have an issue to complete pagination

**Comment by actuallyyun** [comment]
Thanks @clintonlunn !  which api should I call(stg/prod) if I want to consume this data in fe?

**Comment by clintonlunn** [comment]
Great question! I don't know how to consume this info unfortunately. Do you have administrator permissions to see this data when you go to /basecamp/organizations?

**Comment by zichongkao** [comment]
@actuallyyun the `organizations` query should pull these automatically. The catch is that these are added in prod, so you won't have them in dev/staging. So if you want to test how things work in dev/staging, you should add your own test org with associatedAreaIds pertaining to some areas that exist on dev/staging.

**Comment by actuallyyun** [comment]
Thanks for the clarification! @zichongkao  
@clintonlunn  for the reason Kao mentioned, I don't think it's available in `stg/**/basecamp/organizations` yet

**Comment by musoke** [comment]
@clintonlunn, it looks like this is done?
