### ISSUE TITLE
Openbeta community link points to a dead url

### ISSUE THREAD

**Issue by clintonlunn** [OpenBeta/open-tacos#821]
## Steps to Reproduce
[the community link](https://github.com/OpenBeta/open-tacos/blob/develop/CONTRIBUTING.md?plain=1#L28) within the contributing guidelines points to a dead link

## Expected Behavior
There is no longer a message board as it was not utilized much. This link can be removed. 

## Current Behavior
the link points to community.openbeta.io which returns 404
![image](https://github.com/OpenBeta/open-tacos/assets/24685932/2026744e-5e58-4ec1-8906-0f4b8cc6fb8c)

**Comment by clintonlunn** [comment]
@vnugent do we use a message board or are we only on discord nowadays?

**Comment by vnugent** [comment]
we retired the message board lat year due to low traffic.  I think we can remove the community link.
