### ISSUE TITLE
Mispelling 'organizations'

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#831]
## Steps to Reproduce
1.  Go to an area page without a local climbing organization (https://openbeta.io/crag/a354b580-870b-5444-9f11-2c0e78995841)
2. Scroll down to Local Climbing Organizations section. The below misspells 'organizations': 

## Screenshots

<img width="630" alt="Screenshot 2023-05-18 at 7 04 54 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/f0aaf7ab-bc52-4a31-95f4-d6176b10688a">

**Comment by giri-madhan** [comment]
Hi @vnugent, may I work on this issue?
