### ISSUE TITLE
Missing close button in common dialog component

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#837]
The common dialog component used to have a close (X) button on larger screens

## Steps to Reproduce
1.  Go to any area pages and click on the gallery. Example: https://openbeta.io/crag/1db1e8ba-a40e-587c-88a4-64f5ea814b8e

## Screenshots
<img width="500" alt="Screenshot 2023-05-19 at 9 45 31 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/1ca0d7be-8202-4f35-a06d-30c63109af64">

## Expected Behavior
The gallery screen should have a close button on larger screen sizes

## Current Behavior
Button is missing

**Comment by clintonlunn** [comment]
This looks to be happening because of a `md:hidden` added [here](https://github.com/OpenBeta/open-tacos/pull/813/files#diff-2afc2a9f9e027a2fb5a7775ec7c1fd60e5ea743a537ae5df1b9d0a4259a86ebaR30).

**Comment by actuallyyun** [comment]
I added the `md:hidden` in the lco card pr and asked  if this seems like a good idea to you. Maybe you missed this comment in the pr. When I talked with AJ, he said on larger screen, users can just click outside of the dialog to close it, no need for close button. I think it makes sense.

**Comment by musoke** [comment]
Where is one supposed to click to exit the gallery?  This isn't obvious to me.  ESC does work.

This is actually related to a mild annoyance I have: I keep pressing back when I want to exit the gallery and ending up on a different page.  An obvious exit option would help.

**Comment by clintonlunn** [comment]
Since the gallery is full screen modal,   don't think the user is able to click outside of it to exit in this case. 


Since the lco card has a special requirement, maybe we want to add the ability to add custom classes when using the MobileDialog component?

**Comment by actuallyyun** [comment]
I understand the problem now. Will put the exit button back and only remove it from lco card.
