### ISSUE TITLE
Mobile search clicking "Areas" doesn't scroll down

### ISSUE THREAD

**Issue by robbyriley15** [OpenBeta/open-tacos#861]
## Steps to Reproduce
1.  View the site on mobile, hit search
2. Type in a search term
3. Click "Areas"
4. Areas will show as highlighted, however does not scroll down or filter out the climbs. 

## Expected Behavior
I should be scrolled down to the "Areas" section, or it should filter everything else off. 

## Current Behavior
I stay looking at climbs, and am confused :( 

## Browser & version
Chrome 

## Operating system
Android (Pixel 5)

**Comment by musoke** [comment]
As far as I can tell, this has been fixed
