### ISSUE TITLE
Route difficulty counts can't be read due to text color

### ISSUE THREAD

**Issue by robbyriley15** [OpenBeta/open-tacos#862]
## Steps to Reproduce
1. Go to the finder page 
2. click on an area on the map
3. the count of "moderate, intermediate..." climbs blends with the bar color. 

## Screenshots
![image](https://github.com/OpenBeta/open-tacos/assets/9353679/e0595f40-564c-4700-b36f-6f723c017759)

## Expected Behavior
Contrast of text colors should be higher so it's more readable. 

## Current Behavior
The text color is the same so it's hard to read

## Browser & version
Chrome

## Operating system
Fedora

**Comment by vnugent** [comment]
Please use [Daisy UI classnames]( https://daisyui.com/docs/colors/) `text-base-content`



---

To go to the Climb Finder page:
- Click on the search box and enter a city name (Example: Boulder) the click on Address 
- Click on any of the results

<img width="847" alt="Screenshot 2023-06-24 at 10 04 51 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/fb2517dc-d2c9-41a0-a205-7b77e3f18f10">

Search result

<img width="732" alt="Screenshot 2023-06-24 at 10 08 58 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/359b9c56-a5af-4638-9b4d-ca17e9e14d10">

---

**Comment by vnugent** [comment]
@Ali7040

**Comment by Ali7040** [comment]
please assign this issue to me.
