### ISSUE TITLE
CSV editor flagging wrong errors 

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#875]
## Steps to Reproduce

1.Create a new area
2.Mark it as a crag
3.Turn on Edit mode to add climbing routes

## Screenshots

![Screenshot 2023-06-15 at 18 55 28](https://github.com/OpenBeta/open-tacos/assets/87448230/09873eb7-b572-4187-8208-2abe0e1890dd)

The error it flagged is _invalid grades_
## Expected Behavior
Should not flag errors

## Current Behavior
Flag errors about the format
## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

**Comment by musoke** [comment]
I have seen similar errors but haven't been able to narrow them down.

**Comment by musoke** [comment]
@actuallyyun, what parent area did this have?  (Hard to reproduce without knowing the grade context.)

**Comment by actuallyyun** [comment]
Hey it's Sweden/ Niemisel

**Comment by vnugent** [comment]
It may be related to https://github.com/OpenBeta/open-tacos/issues/853 
The code doesn't know how to use grade context to validate user inputs.

**Comment by musoke** [comment]
Yes, creating routes in Sweden will fail for the same reason as #853.  

I had seen similar failures in regions with US context, but have now narrowed down the exact cause.  See https://github.com/OpenBeta/open-tacos/issues/918

**Comment by musoke** [comment]
Csv editor no longer exists
