### ISSUE TITLE
Mountain Project import error 

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#876]
## Steps to Reproduce

1.In production or staging site, go to a profile page
2.Click on Import ticks
3.Add MP link and click on import 
4. Ticks were not imported 
## Expected Behavior

Import ticks 
## Current Behavior

Not importing ticks. 

`VM429:1 Uncaught (in promise) SyntaxError: Unexpected token '<', "<!DOCTYPE "... is not valid JSON
Promise.then (async)`
## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

**Comment by musoke** [comment]
I can confirm.

**Comment by actuallyyun** [comment]
I think the bug is caused by `next-auth`
When clicking on the import button, it calls the `user/ticks` API, then calls `withAuth` , which tries to get the current session. If no session, it redirects users to the signin page, so the initial API call made by `getTicks` function when the button is clicked get a `html` document as response, and caused the error in promise. 
This is the error logged from `next-auth` in dev environment. 
I was logged in so there should be `session` but next-auth did not get it. 
```
[next-auth][error][CLIENT_FETCH_ERROR] 
https://next-auth.js.org/errors#client_fetch_error undefined {
  error: {},
  url: 'http://localhost:3000/api/auth/session',
  message: undefined
}
{ session: null }

```

**Comment by vnugent** [comment]
@actuallyyun this may be it. It may be related to my recent PR in which the signature of `usePermission()` has changed.  https://github.com/OpenBeta/open-tacos/pull/838/files#diff-a1fac38f0272867082ffb0282eeef0e31b834701ac110a211d34fc1a71d1cbd0
