### ISSUE TITLE
Move MP import success message to the center of the screen 

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#891]
**What would you like to be able to do? Please describe.**
Currently the import success message is on the right-down corner of the screen. 
![Screenshot 2023-06-29 at 14 18 46](https://github.com/OpenBeta/open-tacos/assets/87448230/f7bab3f8-467f-44bf-8f40-98f10adb1dd7)

Move it to the center of the screen. 

**How important is this to you** (Please pick one)
- Important

**Comment by vnugent** [comment]
@actuallyyun what do you think if we keep the existing toast notification (to make it consistent with how we notify the user after an action: photo upload, delete, tagging, etc) and immediately direct the user to the tick result page `/u2/username`?

**Comment by vnugent** [comment]
Fixed in https://github.com/OpenBeta/open-tacos/pull/921

The user will be redirected to the new profile page
