### ISSUE TITLE
Duplicate issue templates

### ISSUE THREAD

**Issue by actuallyyun** [OpenBeta/open-tacos#897]
Currently, in the repo, there's `ISSUE_TEMPLATE.md` in the root directory, and there's `ISSUE_TEMPLATE` folder in `/.github` directory. 

I assume the one in the `/.github` directory has priority and is the one we are using now.  

## Expected Behavior
Remove duplicate issue templates. 

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

## Operating system
<--- Example:  MacOS 13.2.1 -->

**Comment by Ali7040** [comment]
I can work on this, just to be clear I have to remove ISSUE_TEMPLATE from the root directory?

**Comment by musoke** [comment]
>  just to be clear I have to remove ISSUE_TEMPLATE from the root directory?

Yes
