### ISSUE TITLE
Add blog link to menu and footer

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#904]
We need to link the to blog on the drop down main menu and footer.

To do
- [ ] Locate the following components:
  - Footer.tsx
  - ProfileNavButton.tsx
  - MobileAppBar.tsx --> More component
- [ ] Add https://openbeta.io/blog 

## Screenshots

Desktop Menu logged in

<img width="331" alt="Screenshot 2023-07-07 at 8 36 50 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/a7bef93c-6596-4eec-9906-baf20a6d3ee2">

---

Mobile menu logged in

<img width="409" alt="Screenshot 2023-07-07 at 8 37 20 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/2ec0cd6d-56dc-43db-8395-d45d9d81cdc9">

---
Desktop & mobile footer

<img width="388" alt="Screenshot 2023-07-07 at 8 37 47 AM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/649e32d6-80fc-4887-959a-a1a184a38162">

## Expected Behavior
we should show link to our blog 

## Current Behavior
link is missing

**Comment by Ali7040** [comment]
I want to work on it. Please assign this task to me.
