### ISSUE TITLE
Search has inconsistent results

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#907]
I am not sure how to title this one, feel free to edit if you have better ideas.  There is some chance that it reproducing it depends on the current state of the DB.

I was searching for https://openbeta.io/climbs/bbacb04a-98fe-50cc-9d2e-b2fac17290bd ("Robbers" on "Gem Boulder, 
The" at "Lynn Woods".)

I expected that "robbers lynn" would give a result quickly.  One of the things I like most about openbeta's search is that queries like this usually work.  As seen in the screenshot, it does not in this case.
![image](https://github.com/OpenBeta/openbeta-graphql/assets/16665084/dcf54e13-f3c8-407e-b3a6-83fbf35900e4)

I thought this might be due to "lynn" and "robbers" being too separated in the tree, but a similar search for "cops lynn" correctly finds a problem on the same boulder.
![image](https://github.com/OpenBeta/openbeta-graphql/assets/16665084/f76a5ee7-daaa-4f61-b43a-a08e5091050c)

"robbers gem" does work:
![image](https://github.com/OpenBeta/openbeta-graphql/assets/16665084/aa41efca-b662-4071-95dd-9832b8fa31bb)

"robbers massachusetts" also works:
![image](https://github.com/OpenBeta/openbeta-graphql/assets/16665084/5b957e15-43bc-44ae-af9b-71fb4971440d)

**Comment by vnugent** [comment]
Thanks for reporting this. I think I have identified the issue.  When searching for climbs, we're not considering area paths (which are important for narrowing down the results)

https://github.com/OpenBeta/open-tacos/blob/develop/src/js/typesense/TypesenseClient.ts#L71
(The searchbox sends 3 queries to search for climbs, areas and FA names respectively in one request)

You should have access to https://cloud.typesense.org/ (log in with your GitHub id) to play with different search queries.  I added `areaNames` and now the right Robbers is the first hit when searching for Robbers lynn woods (or 'robbers mass' or robbers gem').  To fix this we need to update the above query in open-tacos.

<img width="901" alt="Screenshot 2023-07-10 at 7 23 26 PM" src="https://github.com/OpenBeta/openbeta-graphql/assets/3805254/5aba245d-6c65-4e5b-8879-013a4af9ae5f">

**Comment by musoke** [comment]
I don't think I  have access to cloud.typesense.org.  

What you're saying makes sense.  Unclear to me why the other queries did work for me though.  Maybe it will be clearer if I try it myself.

Are there tests for this?  Seems like an easy place to have regressions

**Comment by vnugent** [comment]
I just added you to the DevOps team. Can you try logging in typesense again (using Github id)?  

> Are there tests for this? Seems like an easy place to have regressions
We rarely change the queries going out to Typesense API.  We could add a unit test to make sure the query text  doesn't change.

**Comment by musoke** [comment]
It works now and I agree that you have identified the issue.

The cases that did seem to be using area names weren't - there were a bunch of coincidences in the descriptions that made it appear that way.
