### ISSUE TITLE
unable to tag photos on mobile

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#910]
## Steps to Reproduce

1. Navigate to own userpage on mobile browser (Android Firefox or Chrome)
2. Attempt to tag recent photo with area or route

## Screenshots

![Screenshot_20230712-212734_Firefox](https://github.com/OpenBeta/open-tacos/assets/16665084/f9eabe2e-bc80-4eed-b21b-8a452ef90671)

## Expected Behavior

Tag gets added.

This works on desktop Firefox.

## Current Behavior

Got an error (see screenshot above) and tag is not added.

## Browser & version
<---  Example: Firefox 102.7.0esr  -->

- Firefox 115.0.1 (Build #2015960411),
- Chrome 114.0.5735.196

## Operating system
<--- Example:  MacOS 13.2.1 -->

Android 12

## other

In case there are hints in logs somewhere: most recent attempt was at approximately 01:27:34 UTC.

**Comment by vnugent** [comment]
I can reproduce this on the iPhone
