### ISSUE TITLE
own user profile too wide on mobile

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#911]
## Steps to Reproduce

1. Create an account with a long username
2. Navigate to own profile

## Screenshots

Sorry, this are annoyingly formatted. I don't know if github allows resizing images.

Screenshot of default view.  Note components extending off screen.
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/b5d71fdc-0b85-4511-8197-4c7a821d4bb2)

Screenshot of same page, zoomed out.  Note gap at top right.
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/c3c35dd2-7e20-41a9-90c8-51d3d93713f0)

Screenshot of same page, logged out.  Looks good.
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/8bbbc003-388e-4ee1-a5cb-2ab5b65cdf42)

Screenshot while logged into account with a shorter username.  Looks good.
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/e7b40b52-7724-40ae-a592-c97159a7c079)

## Expected Behavior

 
Should not have to scroll horizontally.

## Current Behavior

See screenshots.  "Edit" link seems to be to blame.

## Browser & version

both
 -   Firefox 115.0.1 (Build #2015960411),
 -   Chrome 114.0.5735.196

## Operating system

Android 12

**Comment by SidV2** [comment]
Should we decrease the font-size or wrap the text?

<img width="420" alt="Screenshot 2023-07-13 at 4 48 59 PM" src="https://github.com/OpenBeta/open-tacos/assets/17374208/6602d4f3-4f0e-40ca-b058-57fb98086fc9">

Above screenshot with xl class removed from username

**Comment by vnugent** [comment]
Besides reducing the font size, can we move the Edit button down to next to Import ticks?  We should also truncate the username is it's too long https://tailwindcss.com/docs/text-overflow#truncate

---

<img width="420" alt="profile-overflow" src="https://github.com/OpenBeta/open-tacos/assets/3805254/5bf74c6c-3fe6-495e-a658-4127adb75e4e">
