### ISSUE TITLE
warn user if tick import errors 

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#913]
Sometimes tick import has an error (e.g. due to #631 ).  It is not obvious when this happens - I have been unsure whether I missed the success notification, it is still processing, or it failed.

Make it obvious.  Briefly say what happened (maybe just say which tick failed). Dev builds could give more details.

Related: https://github.com/OpenBeta/open-tacos/issues/891

**How important is this to you** (Please pick one)

- Important

**Comment by clintonlunn** [comment]
i can probably take this. i added a `toast.error` that will alert when the tick import failed. i think there's still room to add more info. 

in addition, i think this would be a good opportunity to transition the popup box from `react/headlessui/` to `radix-ui/alertdialog`

**Comment by vnugent** [comment]
@clintonlunn Thanks.  Longer term I think we can let users provide their MP and/or theCrag profile URL in their profile settings once.  They can then initiate a re-import any time wish without having to provide a profile URL each time.

**Comment by clintonlunn** [comment]
@vnugent I think that's a great suggestion. Do you have ideas of how/where we can store the mp/crag url?

**Comment by vnugent** [comment]
>  Do you have ideas of how/where we can store the mp/crag url?

We can store it in our DB.  The profile update endpoint will need an update.

**Comment by clintonlunn** [comment]
> > Do you have ideas of how/where we can store the mp/crag url?
> 
> We can store it in our DB. The profile update endpoint will need an update.

I'd be up for completing that work, just not very certain on where to start. But that can be an issue that gets created after this is closed.

**Comment by vnugent** [comment]
We can introduce the profile settings in a separate PR.  After this one is merged, I'd like to get PR https://github.com/OpenBeta/open-tacos/pull/970 in (touching lots of files) so that contributors don't have to deal with merge conflicts.
