### ISSUE TITLE
X icon on tag chips not fully visible on Safari

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#915]
## Steps to Reproduce
1.  Create an account / login openbeta.io using Safari (desktop or mobile)
2.  Go to your profile and upload a photo and add a tag (search for 'Test area')
3. The X icons are partially visible, nearly impossible to click on

## Screenshots

Chrome
<img width="600" alt="chips-chrome" src="https://github.com/OpenBeta/open-tacos/assets/3805254/abd8ab86-6f7d-4383-8f41-702337c8ce58">

Safari
<img width="468" alt="Screenshot 2023-07-13 at 4 42 12 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/40841662-03eb-45c7-9cca-ba29bbb90494">

## Browser & version
- Safari Ventura 13.2.1 
- iPhone X

## Operating system
MacOS 

## Note:
To work on this issue you will need additional API keys in order for Auth0 to work.  Email viet at openbeta dot io

**Comment by hawkishpolicy** [comment]
I am still unable to reproduce this bug.

Running Safari 16.5.2

<img width="1436" alt="Screenshot 2023-07-31 at 12 51 58 PM" src="https://github.com/OpenBeta/open-tacos/assets/123108455/42cbcf38-7680-4711-8f81-2911dd9bac44">

**Comment by vnugent** [comment]
Can you go to Responsive design mode in Safari (Develop -> Enter Responsive Design Mode) to see if you have Safari iOS 16.0?

**Comment by vnugent** [comment]
Duplicates https://github.com/OpenBeta/open-tacos/issues/699
