### ISSUE TITLE
Grade parsing in CSV and climb editors

### ISSUE THREAD

**Issue by musoke** [OpenBeta/open-tacos#918]
## Steps to Reproduce

1. Go to https://openbeta.io/crag/4a6379aa-14e1-5b0c-b77e-b671bb2b98d3
2. Enter edit mode.
3. Observe that the CSV editor has a grey background and does not flag any errors.
![image](https://github.com/OpenBeta/open-tacos/assets/16665084/67a296c2-b0b1-46e8-8ceb-deab6deafb7f)

4. Put cursor at end of first line of csv editor.  Observe that the background is green and no errors are flagged.
5. Add a space " " to the end of the first line in the csv editor.

## Current Behavior

6. See that it now complains about formatting errors, claiming invalid grade on every line - not just the one edited.
 ![image](https://github.com/OpenBeta/open-tacos/assets/16665084/e0ddae28-ba69-4605-8037-ab7a80a5af86)

7. Remove the space. See that the error message persists even though the box content should be the same as was initially presented to the user.

## Expected Behavior

1. Extra whitespace should be allowed in almost all data fields. This is also an issue in the grade edit box for individual climbs.
2. The editor should recognize that the content is valid again when the space is removed. 
4. The error should likely warn that the discipline is incorrect, not grade.

## Browser & version

Firefox 115.0 (64-bit)

## Operating system

Ubuntu

## Related issues

https://github.com/OpenBeta/open-tacos/issues/875
https://github.com/OpenBeta/open-tacos/issues/853
https://github.com/OpenBeta/open-tacos/issues/796 where there are actual errors, but not new errors
https://github.com/OpenBeta/open-tacos/issues/730

**Comment by vnugent** [comment]
This area is designated as a Trad/Sport crag so the validator function uses YDS.  
<img width="500" alt="Screenshot 2023-07-14 at 2 44 53 PM" src="https://github.com/OpenBeta/open-tacos/assets/3805254/1a2106de-1217-4732-b324-b0dfc59dcb9d">

I fixed it by deleting all climbs, switching area type and pasting the old data back.

- Copy existing data in the bulk editor (Ctrl-C)
- Clear bulk editor
- Save
- Switch area designation to Boulder
- Save
- Paste
- Save

**Comment by musoke** [comment]
Ah!
So this was an import error?  I suspect that there are a bunch of these

**Comment by vnugent** [comment]
> So this was an import error?  I suspect that there are a bunch of these

When I coded climb add/edit API, I added a rule to the backend (and later the frontend): **disallow the mixing of boulder problems and Trad/Sport in one crag**.  I introduced a new flag, 'isBoulder = true' to indicate the crag is a boulder.  It has worked well when adding new climbs or boulder problems from scratch.  But for existing 'crags' that are boulder problems (a lot of them in the DB), the flag is not set.

**Comment by musoke** [comment]
Ok, this makes much more sense with that context. 
This is essentially a duplicate of https://github.com/OpenBeta/open-tacos/issues/796.  Maybe there should be a one-time migration to set that flag?

**Comment by vnugent** [comment]
(Temporarily re-open for visibility)

I see 2 actions:
1.  Write a DB script to identify 'crags' containing mostly boulder problems and set the flag
2. Relax the strict "boulder problems only" rule in the backend and the frontend.  Though raise a warning on the frontend if someone attempts to add a rope climb to a boulder.

I'm hesitant with (2) but I think there are exceptions where bolted climbs exist on high ball boulders.

**Comment by musoke** [comment]
Option 1 would be a short term fix for most cases, allowing time to evaluate option 2 as a long term solution.

It wouldn't address cases like you mention, where the mix is an accurate reflection of reality.
In addition to that case:
- The line between highball and free solo is subjective. Examples: https://www.ukclimbing.com/logbook/crags/brown_howe_quarry-19397/ and https://openbeta.io/crag/e24c013f-5724-5919-8b57-fee1d68460e3. In both cases, some people treat it as a boulder problem and others treat it as a rope route.
- Boulder problems that are the beginning of longer routes and don't top out.  They're an odd, but people do boulder on them and it would be clearest to list them in the same area as the longer routes. Example: https://www.thecrag.com/en/climbing/new-zealand/waikato/froggatt-edge/area/196473090


I have seen too many edge cases to feel very prescriptive about much of this and personally favour option 2.  There could even be a warning raised for other editors to investigate - OSM takes this approach (https://wiki.openstreetmap.org/wiki/Quality_assurance)

**Comment by vnugent** [comment]
Filed BE issue https://github.com/OpenBeta/openbeta-graphql/issues/344

**Comment by musoke** [comment]
> 

> I fixed it by deleting all climbs, switching area type and pasting the old data back.
> 
>     * Copy existing data in the bulk editor (Ctrl-C)
> 
>     * Clear bulk editor
> 
>     * Save
> 
>     * Switch area designation to Boulder
> 
>     * Save
> 
>     * Paste
> 
>     * Save

I found a few more boulders with this issue and tried to use this fix.  However, it appears that the descriptions have been lost.  See for example the area https://openbeta.io/crag/177bcbb6-5e6c-5f15-a389-445c791e5e0e - the problem https://openbeta.io/climbs/c0660633-ea59-56b3-a3c3-016e45873bb7 definitely had a description 30 minutes ago.  Does this procedure delete routes from the database before creating a new route with the same UUID?  If so, it makes sense that the description and other data are lost.

**Comment by melissapthai** [comment]
What is the status of this issue? When I go to edit mode, I see a standard looking edit form, not the CSV editor shown in the screenshot. Perhaps that's from an older version of the page? And if so, should this ticket be closed?

**Comment by vnugent** [comment]
@melissapthai yes, the edit forms have changed but the underlying issue is still there. 

@musoke The easiest path moving forward is removing the checks in the backend.  What do you think?

https://github.com/OpenBeta/openbeta-graphql/issues/399

**Comment by musoke** [comment]
Yes, I think it makes sense to remove the checks

**Comment by vnugent** [comment]
@musoke 
Backend task https://github.com/OpenBeta/openbeta-graphql/issues/399 is done.  You can now mix boulder problems and route climbs.
