### ISSUE TITLE
Crag name on the map is duplicated

### ISSUE THREAD

**Issue by baderk** [OpenBeta/open-tacos#940]
## Steps to Reproduce
https://openbeta.io/crag/edb2ca43-0cd8-512b-9ad4-7643b5cf9819
1. Click on a crag
2. Scroll down to the map
3. The name of the crag is in purple box with white font as well as a bigger name behind it in black.

## Screenshots
![Screenshot 2023-07-26 at 6 38 30 PM](https://github.com/OpenBeta/open-tacos/assets/10656279/a60d9626-afcc-479a-acc5-0b3cac272198)

## Expected Behavior
See one label instead of two.

## Current Behavior
Duplicate crag label

## Browser & version
Firefox 115.0.2 (64-bit)

## Operating system
Macos 13.4.1

**Comment by sjsikora** [comment]
It looks like this comes from a broken feature.

From my assumption, the text in the back is supposed to correlate to the location of the main area of the page, and the violet tag would map to the children.

There is broken logic behind this code causing it to write the main name twice, but more importantly, it seems that the area response from the query does not have lat and long metadata of its children.

This area object is defined in /pages/crag/[id].tsx:

```
const rs = await graphqlClient.query<{ area: AreaType, getAreaHistory: ChangesetType[] }>({
    query: QUERY_AREA_BY_ID,
    variables: {
      uuid: params.id
    },
    fetchPolicy: 'no-cache'
  })
 ```
 and looking further into the object shows that the lat and long data is missing

![image](https://github.com/OpenBeta/open-tacos/assets/20007305/d36fc9cc-328a-46c3-b415-e9930c9f22e9)


Any ideas on how to get this data?

**Comment by vnugent** [comment]
@sjsikora 

GQL query https://github.com/OpenBeta/open-tacos/blob/develop/src/js/graphql/gql/areaById.ts#L96-L100

You can add lat, lng fields to the GQL query as follows
```gql
        metadata {
          leaf
          isBoulder
          leftRightIndex
          lat
          lng 
        }

```

**Comment by sjsikora** [comment]
Thank you for the help! I will try to go in and repair this feature.
