### ISSUE TITLE
Create a cloud function to resize photos on the fly

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#944]
**What would you like to be able to do? Please describe.**
We're currently serving photos on openbeta.io from Google storage in full resolution.  Create a Google cloud run function that can resize photos on the fly.

- [ ] Create a resizer cloud function that accepts `width=` parameter
- [ ] Create an API gateway

**How important is this to you** (Please pick one)
- Important

See
- https://maartenvanvliet.nl/2017/07/29/dynamic-image-resizing-with-google-cloud-function/
- https://blog.stefanolaru.com/on-the-fly-image-resizing-with-aws-lambda-s3-and-cloudfront
- https://www.thumbor.org/

**Comment by ccabanero** [comment]
Hello @vnugent - just following up on some requirements:

- What is the preferred runtime/language? For example, Python vs. JavaScript/NodeJS
- Should the cloud function also be invoked on other events vs. HTTP requests from the API Gateway? For example, when an image object is successfully created in Google Cloud Storage (i.e. google.cloud.storage.object.v1.finalzed event), should this cloud function be automatically invoked?

**Comment by vnugent** [comment]
> What is the preferred runtime/language? For example, Python vs. JavaScript/NodeJS

I don't have a strong preference.  It'd be great in Node (less context switching for the volunteers to maintain), but if there's a more performant way in another language we could go with that.

> Should the cloud function also be invoked on other events vs. HTTP requests from the API Gateway? For example, when an image object is successfully created in Google Cloud Storage (i.e. google.cloud.storage.object.v1.finalzed event), should this cloud function be automatically invoked?

Is it something we can add later?  For now I think we can focus on resizing on-demand.  What do you think?

**Comment by ccabanero** [comment]
All sounds good.  I will work through the contributing documentation and pursue any further questions through the team Discord.  Thanks for the reply.

**Comment by vnugent** [comment]
@ccabanero whenever you're ready, email me (viet @ openbeta dot io) I'll need to give you access to our project on Google Cloud.

**Comment by Ugzuzg** [comment]
Can use sharp for image processing: https://sharp.pixelplumbing.com/

**Comment by vnugent** [comment]
> Can use sharp for image processing: https://sharp.pixelplumbing.com/

As long as it performs well for our application I don't have a strong preference.

**Comment by enapupe** [comment]
FWIW I've done something very similar in the past, we "abused" Cloudflare cache on this endpoint so the cloud function would never have to reprocess the same image again. This saved a lot of processing and made things quicker. 
`sharp` seems to be the best option indeed, `webp` seems a good image format choice nowadays BTW.

**Comment by vnugent** [comment]
A few people have expressed interest working on this, but it's still up for grabs.  @enapupe can you help?

**Comment by enapupe** [comment]
I don't have experience with Google Cloud Functions, only AWS Lambda (used in my everyday job). However, I think this would not be an issue if I used a framework like the [serverless framework ](https://www.serverless.com/framework/docs/providers/google/events/http) . 

I'd just need access to the GC to set it up. Also whatever else needed for setting up an actual endpoint (api gateway, dns, etc.

How is this service gonna access the Google storage content? 
edit: also, what about CI and CD? do we have it or just deploy from local machine for now?

**Comment by vnugent** [comment]
Send me an email viet at openbeta dot io and I will give you access to GCloud.  I think GCloud functions is similar to AWS Lambda.

> How is this service gonna access the Google storage content?

- The frontend will request images from the bucket directly. For example: https://storage.googleapis.com/openbeta-prod/u/abe96612-2742-43b0-a128-6b19d4e4615f/Czp7BwrqH9.jpeg

- We can replace the google base url (https://storage.googleapis.com) with our own subdomain, ex: `https://cdn.openbeta.io`

We build the back end with GH action but deployment is manual.  Frontend CI/CD is automated using Vercel.com.

**Comment by vnugent** [comment]
Thanks @enapupe for working on this.  
- Repo for this cloud function https://github.com/OpenBeta/media-server
- Frontend task to switch to new servers: https://github.com/OpenBeta/open-tacos/issues/1013

**Comment by enapupe** [comment]
_For the record, if in the future our google cloud bill for the media server gets too high or the service is perceived as slow:_

It seems CloudFlare now has a dedicated plan/service to handle this sort of things, before we implemented the new media server, any image transformations required at least the Pro plan ($20/mo), it's now an independently billed service, without any upfront cost. 

You mentioned our bill for google cloud compute media server is currently around $16/mo. There's a high chance this new CF business model being cheaper/faster than what we have implemented today. The main differences are the processing speed (CF seems to work 2x faster) and the caching is also warmer than ours with the Free plan, which invalidates quite often - generating more google cloud expenses.

To test it, we would have to:
1) enable it in CF (it costs $0 upfront)
2) change the frontend to point to the new URL 
3) let it run for a month and check the price differences

then, if we want
4) do a bit more setup and use the same media.openbeta.io CNAME (subdomain) and code a tiny worker to keep the exact same API as we have today

**Comment by vnugent** [comment]
@enapupe is this something you could help with?  FYI we're currently using CF R2 for the [crag map tiles](https://openbeta.io/maps) (cost is more competitive than s3)

**Comment by enapupe** [comment]
Yeah I could definitely help with that.
Do you think now it's the right time to make this move? Regarding actually
making a noticable difference right now.

**Comment by vnugent** [comment]
Let's go for it.  The cost saving (if it's indeed cheaper in the long run) is worth it.  I think you still have CF access?  If not, please ping me on Discord.

**Comment by enapupe** [comment]
Ideally we should check the access log for the media server and calculate how many "variations" we have per month, so we can safely invest time in this change. However I'm not sure if such logs exist, maybe cloudflare has some?

It seems the pricing is $1 for 2k transformations. This means we could "generate" 32k image variations and still be in the same ~$16/mo. Do you know how many images we currently have and or a feeling for how many are accessed in a given month? To be clear, the image access itself is free, the variation generation is the only thing that costs.

I have very limited access to CF right now.
