### ISSUE TITLE
"View ticks" button on new profiles causes app error

### ISSUE THREAD

**Issue by sjsikora** [OpenBeta/open-tacos#952]
## Steps to Reproduce

1. Create a brand new profile
2. Navigate to your profile
5. After you create your username, click on the "View Ticks" button on your profile.

## Screenshots

![image](https://github.com/OpenBeta/open-tacos/assets/20007305/ff82f2c6-5176-44a3-b4dc-0910e26650dd)

## Expected Behavior
There should most likely be a screen telling the user that they do not have any ticks.

## Current Behavior
The application crashes. Console log report that "TypeError: Cannot read properties of undefined (reading 'dateClimbed')"

## Browser & version
Chrome Version 115.0.5790.110

## Operating system
Windows 10 Home OS Build 19045.3208

**Comment by gom1** [comment]
I could take a look at this

**Comment by Ali-muhammed7040** [comment]
I hope this message finds you well. I would like to kindly request the assignment of the following issue to myself. Your consideration in assigning this issue to me would be greatly appreciated.

**Comment by musoke** [comment]
@gom1 , are you still working on this?

**Comment by Ali-muhammed7040** [comment]
> @gom1 , are you still working on this?

no I want to start open source contribution that why i'm looking for repo to work on

**Comment by vnugent** [comment]
Fixed by PR #960

**Comment by Ali-muhammed7040** [comment]
please add me on working repo i want to contribute
