### ISSUE TITLE
Web app error on importing Mountain Project Profile Ticks on first attempt

### ISSUE THREAD

**Issue by ccabanero** [OpenBeta/open-tacos#959]
## Steps to Reproduce
1. Logged into to openbeta.io ... https://openbeta.io
2. Navigated to my profile ... https://openbeta.io/u/ccabanero
3. Clicked on the 'Import ticks' button - this opens the 'Input your Mountain Project profile link' modal
4. I copy pasted my Mountain Project profile link ... specifically - https://www.mountainproject.com/user/108656779/clint-cabanero ... then clicked the button 'Get my ticks!'
5. Application error - the web page reports "Application error: a client-side exception has occurred (see the browser console for more information)".  Unfortunately, I did not open DevTools to look at anything logged in the console to report more technical debugging info for this ticket.
6. Important - after trying the above steps a SECOND time (immediately afterwards), my profile import worked.  However, still reporting this as a potential bug as perhaps other target users may not return if they can't import their Mountain Project ticks on the first attempt.

## Screenshots
Screenshot is here [
![](https://klygeo.s3.us-west-2.amazonaws.com/temp/openbeta_apperror.png)
](
![](https://klygeo.s3.us-west-2.amazonaws.com/temp/openbeta_apperror.png)
)

## Expected Behavior
On the first attempt to import my Mountain Project profile, it should work and I should not see a white screen that reports ...  "Application error: a client-side exception has occurred (see the browser console for more information)"

## Current Behavior
Experienced an error on the first attempt.  After trying a second time, the profile import worked.

## Browser & version
Safari Version 16.5.2 (18615.2.9.11.10)

## Operating system
macOS Ventura 13.4.1(c)

**Comment by vnugent** [comment]
I can't reproduce in staging as well as starting from a blank database locally.  I think it's the same as issue https://github.com/OpenBeta/open-tacos/issues/952 which has been fixed after this issue was reported.  

Feel free to re-open if you can reproduce it.
