### ISSUE TITLE
Editing User Profile

### ISSUE THREAD

**Issue by calvincheng919** [OpenBeta/open-tacos#982]
## Steps to Reproduce

https://openbeta.io/account/editProfile

1. Enter Display name
2. Enter Short bio
3. Leave Website blank
4. Click Save

## Screenshots
![Screenshot 2023-09-27 at 10 47 23 AM](https://github.com/OpenBeta/open-tacos/assets/12023140/7f664265-d399-47d9-9776-1d4f61364340)

## Expected Behavior

- Indication of required fields
- Form validation for required fields as the user loses focus
- I understand Display Name should be a required field but should Website be as well?

## Current Behavior

- Clicking "Save" produces above error when Website or Display Name is missing value
- Looks like code is making a round trip post (mutate) to graphQL and coming back with success false if either field is missing

## Browser & version
<---  Example: Firefox 102.7.0esr  -->
Chrome Version 117.0.5938.92 (Official Build) (arm64)
## Operating system
<--- Example:  MacOS 13.2.1 -->
MacOS 13.5

**Comment by vnugent** [comment]
This is actually a backend bug.  The update profile API should allow a blank website address, ie, the user previously provided a value and want to clear it.

**Comment by vnugent** [comment]
@calvincheng919 I've made a backend fix.  Can you please verify if this is still an issue?

**Comment by calvincheng919** [comment]
Hi Viet, apologies for being silent... been on vacation and getting back to
work has been met with quite the barrage of communication.

I sure can test and verify.

**Comment by calvincheng919** [comment]
Hi Viet, I can confirm this is no longer an issue.

Thanks!

**Comment by vnugent** [comment]
@all-contributors add @calvincheng919 for bugs

**Comment by calvincheng919** [comment]
woohoo! thanks Viet!
