### ISSUE TITLE
Login Button Overlaps on to Search Bar

### ISSUE THREAD

**Issue by sjsikora** [OpenBeta/open-tacos#985]
## Steps to Reproduce

1. Compress your browser to these intervals:
[1280, 1536] px x any height

## Screenshots
When the browser has a 1280px width:
![Screen Shot 2023-10-02 at 12 28 12 PM](https://github.com/OpenBeta/open-tacos/assets/20007305/c2bec616-6cc3-456c-aea1-be4fc5ab1eca)

When the browser has a 1536px width:
![Screen Shot 2023-10-02 at 12 28 39 PM](https://github.com/OpenBeta/open-tacos/assets/20007305/7530328a-1f50-4683-a548-cb3b158d5f49)

## Expected Behavior
The login button should have its own room.

## Current Behavior
The login button overlaps on the search bar

## Browser & version
Chrome Version 117.0.5938.92 

## Operating system
macOS Monterey 12.6

**Comment by irfanfaraaz** [comment]
@vnugent Can i work on this?

**Comment by vnugent** [comment]
@irfanfaraaz I've assigned it to you.  Please share some some screenshots of your fix.  Thanks!

**Comment by irfanfaraaz** [comment]
At 1500 px
<hr/>

![image](https://github.com/OpenBeta/open-tacos/assets/87533725/ec8667fe-350c-4bce-ac64-23263b6195fc)

<hr/>


at 1200 px
<hr/>

![image](https://github.com/OpenBeta/open-tacos/assets/87533725/a1f9ebb5-a526-4d31-b35d-682b3771eaa0)



@vnugent

**Comment by vnugent** [comment]
Fixed in #987
