### ISSUE TITLE
Prevent map from zooming when scrolling area/climb screen

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#993]
## Steps to Reproduce
1. Go to an area page such as https://openbeta.io/crag/bea6bf11-de53-5046-a5b4-b89217b7e9bc
2. Scroll to the end of the screen until the map is visible
3. At this point the map will capture the mouse scroll events (by the wheel or gesturing), interfering with the ability to scroll the to the top of the page

## Expected Behavior
I want to be able to scroll up and down.  This page has a good example https://docs.protomaps.com/
you  have to use Ctrl or ⌘ key to scroll

Also test the fix in mobile view to make sure when can pinch zoom and scroll

## Current Behavior
Hard to scroll when viewing the map

**Comment by Ali-muhammed7040** [comment]
@vnugent   I want to work on it. please assign it to me.

**Comment by Ali-muhammed7040** [comment]
thank you.

**Comment by ShravaniRoy** [comment]
@vnugent I am a first-time contributor. I am able to set up the project and reproduce the issue. Can you assign it to me?

**Comment by vnugent** [comment]
@Ali-muhammed7040 how are you doing with the fix?

**Comment by Ali-muhammed7040** [comment]
> @Ali-muhammed7040 how are you doing with the fix?
I'm doing it will be submited in 24 hours.
