### ISSUE TITLE
Cannot add new boulder problems

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#999]
## Steps to Reproduce
1.  Go to a boulder
2. Enter edit mode
3. Type a new boulder problem in the text editor.  Error:  Please fix formatting error.
## Expected Behavior
I can add new problems

## Current Behavior
Error.  The frontend checks to see if the `isBoulder = true` before allowing users to add new problems.  By default, this flag is not set in the db for all boulders (area data type).

**Comment by musoke** [comment]
Possibly related to #918, which I coincidently just ran into again?

**Comment by vnugent** [comment]
You're right.  I'm closing this one and bump #918 for visibility.
